#+TITLE: Gentrification in London: a progress report, 2001–2013
#+AUTHOR: Alex Fenton
#+PROPERTY: header-args:R :session *R-LondonGrowthPoverty* :cache yes :exports results
#+OPTIONS: toc:nil
#+LATEX_CLASS: koma-paper
#+LATEX_HEADER: \IfFileExists{case-paper.sty}{\usepackage{case-paper}}{\usepackage{biblatex}}
#+LATEX_HEADER: \addbibresource{everything.bib}

#+TOC: headlines 2

#+BEGIN_LaTeX
\ifdef{\CASEcontact}{\CASEcontact{XXX}{June 2016}}{}
\clearpage
\listoftables
\listoffigures
\clearpage
\ifdef{\CASEboiler}{\CASEboiler{Alex Fenton}}{}
#+END_LaTeX

* Editorial note and acknowledgments
  :PROPERTIES:
  :UNNUMBERED: t
  :END:
  This paper was written from 2013 to 2015 whilst the author was a Visiting Fellow at CASE, and has benefited from ongoing exchanges with colleagues at the centre. Some of the analyses and sources here, including the UMBR dataset, build on research conducted in 2011 and 2012 as part of the /Social Policy in a Cold Climate/ programme at CASE, funded by the Nuffield Foundation, the Joseph Rowntree Foundation and the Trust for London. Hannah Aldridge (New Policy Institute) and Antoine Paccoud (LSE) read an earlier draft of the paper and provided valuable comments. Abigail McKnight made numerous editorial improvements. Remaining errors are the author's responsibility.

  The paper used microdata from the /Family Resources Survey/ and /Households Below Average Income/, to which access was provided by the UK Data Archive at the University of Essex. It also used 2001 and 2011 Census tables, provided by NOMIS, and administrative data from DWP (benefit claim statistics), HMRC (personal tax data) and VOA (Council Tax data). Crown Copyright on these materials is acknowledged as applicable.  The income simulation and analysis of the results was carried out in R statistics with extensive use of several packages, notably "survey" [[cite:lumley_survey:_2014][;]], "ggplot2" [[cite:wickham_ggplot2:_2015][;]] and "Hmisc"  [[cite:harrell_jr._hmisc:_2015][;]]. The source code for the analyses presented in this paper as well as R code, data and output weights for the spatial microsimulation are available online at https://github.com/a-fent/microsim-ipf.

* Abstract
  :PROPERTIES:
  :UNNUMBERED: t
  :END:
  This paper investigates changes in the composition and spatial distribution of income poverty in London from 2001 to 2013, and considers them as evidence of gentrification. It is first argued that income poverty measures address some of the shortcomings of conventional occupational class statistics in gentrification research. The empirical analysis, using poverty proxies and spatial microsimulation income estimates, show that in the poorest, eastern parts of inner London, poverty rates fell. Here there was intense development and valorisation of land and housing around the financial districts, rapid population growth, and absolute falls in the numbers of the out-of-work poor. Poverty rates rose in the relatively disadvantaged parts of outer London. This is accounted for partly by rises in out-of-work poverty, but predominantly by the impoverishment of low-income workers through their wages becoming insufficient relative to housing costs. The paper thus confirms broad changes in the spatial distribution of poverty identified in recent studies, while pointing to the exploitation of labour and land as central mechanisms in explaining patterns of gentrification and proletarianisation in the city.

#+BEGIN_LaTeX
\ifdef{\CASEkwords}{\CASEkwords{London, gentrification, poverty}}{}
\ifdef{\CASEjelnum}{\CASEjelnum{R230}}{}
\ifdef{\CASEcorresp}{\CASEcorresp{alex.fenton@pressure.to}}{}
#+END_LaTeX

* Introduction
  After decades of population decline after World War 2, London has undergone a remarkable reversal of fortunes since around the mid-1980s. In the first decade of the 2000s this was apparent in official statistics, which showed how London increasingly drew apart from the rest of the UK in measures of aggregate economic performance. It was equally visible in the physical form of the city, which became denser and taller and — according to taste — either adorned or blotted by new "landmark" buildings providing offices, leisure and residence to an international economic elite. Economic growth and physical development were, however, spatially uneven processes. They were uneven in the sense that London, taken as a whole, diverged further from its hinterland, the rest of the UK, but also in that this growth and development was most pronounced in certain parts of the inner urban area.

  Some of the same parts of inner London appear, according to deprivation indices, to have undergone considerable change in their socio-economic composition. For decades up to the turn of the century and beyond, some of London's inner districts featured as among the most deprived in Britain according to official indices. The worsening of social conditions in these areas in the 1980s drew the attention of major poverty reports in the 1990s[[cite:barclay_joseph_1995][pp.7-9,29-31,54;]]. In the 2004 English /Indices of Multiple Deprivation/ (IMD), based on 2001 data, boroughs like Hackney, Tower Hamlets, Newham and Islington had intensity and extent of neighbourhood deprivation comparable to the most disadvantaged urban districts of the de-industrialising north in Greater Manchester, Merseyside and Humberside. The report on the most recent edition of the IMD, 2015, identifies several of these same boroughs as having the rapidest falls in some measures of relative deprivation since the previous (2010) edition, sufficient to take them out of the "top 20" most deprived nationally[[cite:gill_english_2015][pp.11-15;]]. This confirms a trend already observable in 2010[[cite:leeser_english_2011][;]].

  That said, other recent observers have pointed to aspects of continuity and stability in London in the 2000s. Of central importance to this paper, overall rates of income poverty barely changed in London over the decade from 2000, nor indeed from 2010 to the present [[cite:aldridge_londons_2015][p.23;]]. Poverty after housing costs, the most meaningful official measure available, remained at around 27-28% of London's population, and thus far above poverty rates in the rest of the UK. This paper presumes that the presence of both remarkable economic growth and persisting income poverty required a common explanation, and should not be taken, as in commonplace comment, as a paradox and a puzzle[[cite:massey_world_2007][pp.54-55;]]. In this connection, it may surprise some to learn that household income inequality in London did not, by some common measures, increase over the decade[[cite:aldridge_londons_2015][;]]. Furthermore, analysis of censal data points to a new stability over the last decade in the (occupational) class structure of London, which in previous decades had shown evidence of a continuing "professionalisation" and decline of the "traditional" working class[[cite:manley_london:_2014,hamnett_changing_2015][;]]. From Census data, authors have concluded "London remains an extremely diverse place socio-economically, and … over the decade 2001–11 changes in its socio-economic class structure and associated geography have not been extensive"[[cite:manley_london:_2014][p.642;]].

  In this context this working paper has two purposes. The first, pursued in the main empirical section below, is to present new evidence on changes in the spatial distribution and composition of income poverty in London over the decade from 2001 to 2011. This confirms some of the findings already alluded to, such as notable falls in income poverty in some inner London boroughs. In addition, however, it demonstrates the significance of housing development and of local differences in the composition of poverty to the interpretation of these findings.  The second aim of the paper, developed in the section which immediately follows, is to argue for the use of income poverty data as quantitative evidence for gentrification as a supplement to the Census occupational class data which have been the prevailing focus of the recent British academic literature. Taking in-work poverty as an index of labour exploitation, the paper concludes that there is not only clear evidence of gentrification in much of Inner East London, but also of proletarianisation in some of the relatively disfavoured parts of Outer London.
** Poverty research and gentrification studies
   This paper adopts a descriptive and empirical stance towards the exclusively quantitative data it reports. One cannot pretend, however, that these quantitative data, any more than any other, merely present themselves, /wertfrei/, ready to be tidied up, shuffled into graphs and decorated with some descriptive text. It is useful, therefore, to look briefly at two principal fields of debate in which data about the distribution of poverty and class have been used, analysed and represented. I label these fields of debate "urban poverty research" and "gentrification studies". Identifying these two strands is partly a preliminary to the main argument, but serves also to point out that the formal exchanges, such as citation and reference, have remained rather limited between the two fields.

   The terminology and concerns of the first field, "urban poverty research", will be recognisable in much of this paper. In this field, income poverty is one a series of economic and social problems which have emerged or appeared starker over the course of the last decade in London. The unchanged prevalence of poverty in London is a problem in itself, one prominent link in a chain of connected public problems, like inequality, housing, migration, pay, welfare benefits, taxation, governance and so forth. These problems lend themselves to empirical analysis. Such analyses are connected to and taken up in policy debates, to support claims for the importance of issues, and about which interests ought to be favoured in policy in these discrete fields: should planning restrictions be relaxed? should housing subsidies be reduced? should London have its own minimum wage?

   It is not this paper's purpose to take in all recent work on poverty and inequality in London, let alone to venture along the chain of problems and their associated social scientific analyses. Two series of such publications, however, nicely exemplify both the concerns of such research and its contribution to the empirical material which follows here. The first series are the /London Poverty Profiles/ produced by the New Policy Institute [[cite:aldridge_londons_2013,aldridge_londons_2015][;]]. These provide comprehensive analysis of data on poverty, inequality and deprivation in London, accompanied by illuminating commentary. The last (2013) /Profile/ noted the tendency of poverty to move outwards in London and the differential effects of recession on jobs in Inner and Outer London, further contributing to this trend. The reports also note the prevalence of low pay in London: that is, wages which even in full-time employment are insufficient to provide basic living standards. A corollary of this is the extensive and growing dependence of many employed Londoners on Housing Benefit or Local Housing Allowance to meet their rent.

   The second series is work on London's distribution of income at the Centre for Analysis of Social Exclusion[[cite:lupton_prosperity_2013,vizard_changing_2015][;]]. CASE's reports focus rather more on changes in the distribution of income, wages and wealth, and the consequences of these for measures of inequality. CASE's analyses are usefully divided into two time periods, and these divisions will be pertinent to the interpretation of the findings presented here. The first report covered the period from 2001 to 2007, a period of relatively stable accumulation, modest growth in wages, and modest falls in poverty. The more recent publication reprises these analyses from 2007 to 2013, from the banking crisis and ensuing recession to the first half or so of the period of Coalition goverment from May 2010 to May 2015. The researchers argue that the early half of this period after the financial crisis saw lower real incomes relatively protected, as household incomes were protected by both the "automatic stabilisers" of the welfare system and the counter-cyclical fiscal policy of the government to 2010. However, with austerity — and even before the implementation of cuts to social security benefits —real incomes fell sharply from 2010, and fell most at the bottom end of the income distribution. As the NPI reports, CASE's authors attach central importance to housing costs and low pay as explanations of explaining rising poverty and income inequality in London in the period from 2007 as whole [[cite:vizard_changing_2015][p.14;]]. This paper, then, is intended in part as a contribution to the line of policy-oriented investigation of poverty undertaken in these reports and elsewhere.

   "Gentrification studies" is another field in which sustained empirical attention has been paid to changes in the socio-economic composition of the city, albeit one in which the neighbourhood rather than the city takes centre stage. There has been a whole subgenre — arguably a distracting one [[cite:slater_eviction_2006][;]] — of work on the definition of gentrification. For the purpose at hand, gentrification is understood as changes in the composition and character of urban localities in favour of newer residents with more resources and at the expense of existing residents with fewer resources; I will return shortly to the reasons for the awkwardness of this formulation. An important development of work on gentrification since around 2000 has been to underscore that such observed changes are not simply local consequences of arbitrary changes in fashion and taste. Gentrification is, rather, closely connected to urban inequality, uneven access to housing and other resources, and economic organisation, and, further, gentrifying neighbourhoods are produced, with state policy on land, housing, and welfare having an instrumental role [[cite:hackworth_changing_2001][;]].

   Here we see some of the terms of art of urban poverty research — inequality, policy, economic growth — recurring. However, it is only really in housing policy that there has been a much sustained engagement between policy-oriented research and academic or activist work on gentrification. Within Britain, at least, the bulk of empirical quantitative research on gentrification has operationalised its object through the use of housing tenure or occupational class variables, and has drawn mostly on the Censuses of Population. Income poverty and deprivation analyses have attracted relatively little attention. There are reasons for thinking this may have been a missed opportunity.
** Class and poverty as indices of gentrification
   The preceding  working definition of gentrification used the ungainly phrase "residents with more [or fewer] resources" to describe its central empirical claim. Why not refer to owner-occupiers and renters, or to the middle and working classes? And what virtue might there be in the use of income poverty as a index of gentrification? Whilst there is almost certainly consensus that gentrification involves an inequality of status, resources or power between the existing and incoming residents, there is rather less on what dimension is important, and, crucially, how it ought to be measured. This varies between countries, even within the english-speaking world, with a British emphasis on social class and an American emphasis on income, not to mention the significantly different configurations of tenure and race in the respective countries. It also varies between authors, and even single authors in a single text sometimes slide between referring to, say, "middle-class" and "more affluent" households.

   Classic accounts of gentrification, such as the early work of Ruth Glass and Neil Smith noted changes in tenure from renting to owner-occupation as a index of neighbourhood gentrification. But in London, say, with a large, growing and differentiated private rented sector, there is no reason to suppose that "upward" changes in socio-economic composition should correspond in any simple way to changes in tenure composition. This holds even if, conversely, given tenure changes such as the removal of social tenants might with certainty entail changes in social composition. For this reason, even if housing policy and economics rightly remain salient in the study of gentrification processes, housing tenure itself is of limited use in measuring gentrification.

   In recent British research at least, it has been claimed that there is "wide agreement that class should be the undercurrent in the study of gentrification" [[cite:slater_eviction_2006][p.742;]]. The problem however remains that it is not obvious what conceptualisation of class is the appropriate one, nor how such a concept might be operationalised in order to perform a quantitative assessment of gentrification. There are longstanding sociological disputes about the fundamental basis and measurement of class [[cite:nichols_social_1979,wright_understanding_2009][;see for example]], and an equally longstanding tradition of describing and disputing changes in class structure and class relations. Recent attempts to refound class classifications have not received general acceptance within social science, with objections on both conceptual and empirical grounds [[cite:savage_new_2013,mills_great_2014][;]]. Such reformulations are yet further from the adoption into official statistics which would be a prerequisite of their use in large-scale empirical work.

   British official statistics have in recent decades in the Census settled on a primarily occupation-based class scale, the NS-SEC. The use of such statistics in more or less their given form has produced work of considerable empirical value, such as recent analyses comparing the 2001 and 2011 spatial distribution of NS-SEC classes in London [[cite:manley_london:_2014][;]]. However, even in such careful work, the limits of occupational class become apparent. One is the treatment of "intermediate" classes, that large body of people who are neither unambiguously middle- or working-class in a traditional sense. Even authors who use such classifications admit that this is a class — if such it can justly be termed — which "has become a major feature of inner London's more mixed, residential landscape" but "some of whose members have affinities with the middle rather than the working class and vice versa [[cite:manley_london:_2014][;]]. At the same time, such analyses are bedevilled by concurrent changes over time in local composition and city-wide class-structure [[cite:hamnett_gentrification_2003,hamnett_new_2009][;]]. One response to such difficulties has been to reject the uncritical use of occupational class statistics with their central emphasis on employment relations as an inadequate operationalisation of class [[cite:slater_still_2010][pp.172-73;]].

   Such critique, however, still does not answer the wish for a measure that might be used in quantitative study of gentrification. Using measures of low income or income poverty as indices of gentrification is familiar in the US literature, but less so in the British context. Erik Olin Wright, however, has argued the case for looking at poverty as a consequence of class relations specific in "The Class Analysis of Poverty" [[cite:wright_interrogating_1994][Ch.2;]]. More specifically, he starts from a concept of exploitation, it being "a particular type of antagonistic interdependency of material interests of actors within economic relations", and specifies three criteria for it, inverse welfare, exclusion and appropriation [[cite:wright_interrogating_1994][;]]. From these he derives two sub-types of poverty: "the working poor" and "the underclass" [[cite:wright_interrogating_1994][pp.46ff;]]. Briefly put, the former are those both oppressed and exploited, the latter those who are oppressed and excluded, their labour power unwanted or unneeded in capitalist production.

   For our present purpose, the value of Wright's insight is to suggest that income poverty is, if not class itself, an indicator of position in class relations[fn:7]. It thereby suggests a way of using an operationalisable construct, poverty, to conduct empirical analysis of gentrification. It answers one of the difficulties of occupational class constructs, that of those people neither middle- nor working-class by giving an unambiguous criteria: the "working poor", those who sell their labour yet receive insufficient recompense to provide a normatively minimally adequate standard of living, count among those with less access to resources.

   A further attraction of the scheme is the analytical distinction it draws between working poverty and out-of-work poverty within class relations. This allows us to distinguish the displacement or absorption into the labour market of "the underclass" (to use Wright's term) from the prevalence of exploited labour or proletarianisation. A key finding from the empirical analysis that follows is the spatial divergence of these trends in London over the 2000s. A further advantage is that, by using poverty standards which include housing costs, the concept of exclusionary access to resources is extended beyond the employment situation to property relations in housing. Thus the price of housing and access to it are drawn into the definition of position in class relations. Thus, the analysis shows both if and where privatisation and commoditisation of housing withdraws it from the reach of the "underclass", and where people remain or fall into exploitative relations.

   This paper certainly does not make the claim that income poverty is obviously superior to all other measures as a yardstick for measuring  gentrification. Before turning to the methods used, a couple of conceptual shortcomings of poverty as a gentrification measure should be noted. One is that, just like occupational class, any actual operationalisation of income poverty is conventional and to some degree arbitrary. Those who are defined as "poor" according to one poverty threshold and set of ancillary conventions (household-size equivalisation, treatment of housing costs) may not be by another.  It is not claimed that the particular operationalisation of poverty that, as described shortly, is used in the empirical analysis is the best. It is, rather, currently well-known and widely used, and incorporates the central concept of a household income sufficient to provide a minimal normatively acceptable standard of living, even if the definition of that standard is to some degree arbitrary.

   It has already been said that poverty is not itself class, but is useful as an indicator of position in class relations of exploitation. Poverty may be a transitory state, whereas class, sociologically, implies a relatively durable characteristic of persons, with subjective and inter-subjective dimensions, and a principle of social stratification of which money is a part, but not the whole. Using poverty statistics as an index of gentrification has nothing to say about possible changes in the character of neighbourhoods, and the important social and cultural dimensions of inclusion, exclusion and displacement in them. The following analysis does not imply that those are considered unimportant or epiphenomenal.

   The concept of displacement is both central and contentious in gentrification studies. There is debate, for example, about whether some kinds of "redevelopment" in British cities proceed without displacement of existing residents, and are thus not "gentrification" [[cite:davidson_new-build_2010][;Many contributions to this debate are reviewed in]]. Certainly the provision of positive evidence that existing residents have been physically displaced sets a high burden of proof on those who wish to claim that  gentrification is taking place[[cite:slater_eviction_2006][p.748;]]. Not only must something be shown to have occurred (people moving away, a change in the character of the neighbourhood), but this change must also be shown to be attributable to the recomposition of the neighbourhood and be demonstrated to be involuntary or disadvantageous.

   Most poverty statistics, including those shortly presented, are cross-sectional counts or rates for spatial units, and thus provide no more evidence than Census data on displacement. The analysis that follows has nothing direct to say about the changing circumstances of individuals and households over time, let alone the structure of motivations and constraints within which such changes have unfolded. Nonetheless, since the poverty concept used is centrally one of unequal material access to resources, at least some moves of households between areas reflect not choice, but a lack of it. Thus area aggregate changes in poverty may be evidence for, if not a demonstration of, gentrification. Furthermore, we should apply a similar burden of proof to sanguine interpretations of neighbourhood falls in poverty, which explain them through the beneficial workings of the economy, labour market policy or efforts at social inclusion.
* Methods and Sources
  The empirical analysis which follows seeks to describe changes in the spatial distribution of income poverty from 2001 to 2011; one dataset used allows the analysis to be extended to 2013. These are, as already noted, conventional comparisons of cross-sectional area data, albeit data hitherto not used for such analysis, and in part wholly new and presented here for the first time. In addition, matched information on population density and on housing development are given in support of parts of the interpretation given to the results. Two complementary approaches are adopted to the description of changes in the spatial distribution of poverty. One uses standard small-area spatial units comparing a poverty proxy rate over time. The other, drawing on the differentiation discussed above between the "underclass" and the "working poor", looks at area changes over time in the composition of poverty. For the sake of tractability of analysis and intelligibility of results, the larger spatial scale of boroughs is employed in this analysis. At neither the small-area nor the district scale are standard UK official survey measures of income poverty (derived from the /Family Resources Survey/) available. The analysis thus employs two techniques to overcome this absence, administrative proxies for poverty and estimation of income distributions by means of spatial microsimulation.
** Administrative poverty proxies
   The first section uses a proxy measure of area poverty rates, the /Unadjusted Means-Tested Benefits Rate/ (UMBR). This dataset, produced by CASE as part of the /Social Policy in a Cold Climate/ programme, provides observations annually from 2001 to 2013 for around 40,000 small geographic units in Britain, including somewhat under 5,000 in London; it is publicly available [[cite:fenton_unadjusted_2015][;]]. UMBR is based on administrative data on major means-tested social security benefits, such as Income Support and Job-Seeker's Allowance. 

   Receipt of such benefits is a very strong predictor of income poverty at the household level, and area rates of receipt have a strong linear corelation rates of income poverty as measured by sample surveys [[cite:fenton_small-area_2013][;]]. UMBR rates, which are denominated by estimated number of households, are not directly poverty rates, but are a validated proxy for them. For the present purpose the advantages of this dataset lie in its geographic detail and consistent measurement for the period of interest. It is measured to UK-standard geographic boundaries, which enable it to be linked to other data sources, as here, where it is examined against administrative data on dwelling value and numbers.
** Spatial microsimulation of income
   One disadvantage of UMBR is that it incorporates a set of essentially administrative definitions of low income (means-test thresholds), rather than statistical ones. Variation over time and space in the relation between administrative definitions and a "real" income-poverty concept are not easily quantified; UMBR does not, for example, contain any direct observation of low wages or of housing costs. There are also systematic differences between areas and between population subgroups, some of whom are geographically concentrated, in the take-up of means-tested benefits that are included in UMBR [[cite:bramley_benefit_2000][;]]. This is a cause of error in them as a poverty estimate, with the scale of this error hard to quantify. Lastly, UMBR provides only a single household rate per-area per-year; no information on other characteristics of the poor or the non-poor is given. 

   For all of these these reasons, the second empirical section uses income estimates derived from a spatial microsimulation to describe changes in the composition of poverty at the level of boroughs. The following is a brief overview of this method; it is treated more extensively in an accompanying working paper, /Microsimulation estimates of household income distributions in London boroughs, 2001 and 2011/.  The spatial microsimulation estimates are produced by combining multiple local area census tables and tax data with detailed sample survey information on income from the /Family Resources Survey/ and /Households Below Average Income/ series. The survey years used are 2001/02 and 2011/12, which are used with 2001 and 2011 Census data respectively. The survey cases from these years, with their detailed information on income, are "matched" or "fitted" to household and adult characteristics in the local area by adjusting the survey weights.  The survey population is thereby made to resemble the local population on income-predicting dimensions such as age, sex, occupational class, taxable income and household type. 

   This matched and reweighted survey data can then be used to estimate whatever features of the local income distribution are of interest. This includes points in the distribution (deciles, mean, median) and income-poverty rates by different thresholds and income definitions. Unlike UMBR, these poverty and income statistics are not proxies but direct measures. These microsimulation estimates, whose underlying sources are independent of those used in UMBR, have two main virtues for the following analysis. Firstly, they measure income poverty directly in conventional terms, accounting for household size and housing costs, and, secondly, they permit examination of the prevalence of poverty in population subgroups.
* The Spatial Redistribution of Poverty
#+NAME: my-libraries
#+BEGIN_SRC R :exports none :results output silent
  library(readr)
  library(ggplot2)
  library(reldist)
  library(plyr)
  library(reshape2)
  library(data.table)
  library(scales)
  library(gridExtra)
  source("../r/ipf_functions.r")
  source("chart_style.r")
  # Definitions of London boroughs, names
  source("little_helpers.r")
#+END_SRC
#+NAME: my-secret-setup-umbr
#+BEGIN_SRC R :exports none :results output silent
  if ( ! exists("umbr.l") ) {
    umbr <- read_csv("~/Documents/Purgatory/umbr14/umbr14-esw.csv")
    # LSOA to LA, London only
    oa.11.lookup <- read_csv("~/Documents/Purgatory/borders/oa_lsoa_msoa_la_lookup.csv")
    lsoa.2.la.ln <- subset(oa.11.lookup,
                           ! duplicated(LSOA11CD) &
                           (LAD11NM %in% borough.defs$LA.NAME))
    umbr.l <- merge(umbr, lsoa.2.la.ln,
                    by.x="Geogcode", by.y="LSOA11CD")
    umbr.l <- merge(umbr.l, borough.defs,
                    by.x="LAD11NM", by.y="LA.NAME")
  }

  # Hexagon design
  if ( ! exists("umbr.hex") ) {
      # Centroids
      lsoa.hexes <- read_csv("hex_map_outlines/hex_lsoa_memberships.csv")

      umbr.hex <- data.table(merge(umbr.l, lsoa.hexes,
                                   by.x="Geogcode", by.y="lsoa"))
      # The ggplot map outlines to go with this
      base.hex <- read_csv("hex_map_outlines/hex_outlines_hexes.csv")
      la.hex <- read_csv("hex_map_outlines/hex_outlines_la.csv")
      # Ensure drawing discontinous hexagons separately
      la.hex$la.group <- paste(la.hex$la, la.hex$piece)
      # This is old NUTS3 - i.e. new NUTS2
      nuts3.hex <- read_csv("hex_map_outlines/hex_outlines_nuts3.csv")
  }

  # Outline overlay for multi-map presentation
  la_overlay_thin <- geom_polygon(data=la.hex, aes(group=la.group),
                                   fill="transparent", colour="white", size=0.25)
  n2_overlay_thin <- geom_polygon(data=nuts3.hex, aes(group=n3),
                                   fill="transparent", colour="#666666", size=0.25)
  # Outline overlay for thin-map presentation
  la_overlay_thick <- geom_polygon(data=la.hex, aes(group=la.group),
                                   fill="transparent", colour="white", size=0.4)
  n2_overlay_thick <- geom_polygon(data=nuts3.hex, aes(group=n3),
                                   fill="transparent", colour="#666666", size=0.4)
#+END_SRC
Figure \ref{fig:umbr-distribution} presents the distribution of poverty, based on the UMBR proxy, across London in four years between 2001 and 2013. In the diagram around 4,800 base areal units, Lower-Level Super Output Areas,  are grouped into hexagonal zones. The space allotted to inner London is increased to show the geographic trends more clearly. The approximate boundaries of the five NUTS2 areas of London, based on the Office for National Statistics definition[fn:2], are outlined with grey lines, whilst the approximate borough boundaries are shown in white.

The picture presented will be familiar from any number of mappings of income poverty, material deprivation and social exclusion based on a wide variety of sources [[cite:mclennan_english_2011][p.69;For example, ]]. It shows the highest concentrations of poverty in inner East London, particularly in the boroughs of Hackney, Tower Hamlets and Islington, and extending into parts of Islington, Southwark and Lambeth. Although the areas with the absolute highest poverty in 2001 were in inner London, parts of outer London also have high poverty rates, notably in Brent, Croydon and Enfield.

#+NAME: fig:umbr-distribution
#+BEGIN_SRC R :results output graphics :file fig/umbr-hex-distr.pdf :width 4.5 :height 3.5
  hex.rates <- umbr.hex[,list("All.MTB"=sum(All.MTB, na.rm=TRUE),
                              "Hholds"=sum(Hholds, na.rm=TRUE)),
                        by=c("Year", "hex.id")]
  hex.rates[,UMBR:=All.MTB/Hholds]

  hex.toplot <- merge(base.hex, hex.rates, by.x="id", by.y="hex.id")
  hex.toplot <- subset(hex.toplot, Year %in% c(2001, 2006, 2009, 2013))

  # Must be in correct order to plot correctly
  hex.toplot <- hex.toplot[order(hex.toplot$Year,
                                 hex.toplot$id,
                                 hex.toplot$order),]

  ggplot(data=hex.toplot, aes(x=long, y=lat, group=group)) +
      geom_polygon(aes(fill=UMBR), alpha=1) +
      scale_fill_gradientn("UMBR", colours=c(blue, grey.1, red.1,  red.2, red.3),
                           guide="colorbar", label=percent) +
                           la_overlay_thin + n2_overlay_thin +
      facet_wrap(~Year) +
      coord_equal() +
      the_map_theme_legend_right
#+END_SRC

#+LABEL: fig:umbr-distribution
#+CAPTION[The UMBR poverty proxy rate in selected years in London since 2001]: Map of the distribution of UMBR poverty proxy rate (claimants/households) in London, 2001, 2005, 2009 and 2013. Drawn area sizes adjusted towards population size. The dark grey and white lines show the approximate outlines of the NUTS2 divisions and of individual boroughs respectively.
#+RESULTS[1d1b66bca78aa525b3f5e215e26b4a53dc3846df]: fig:umbr-distribution
[[file:fig/umbr-hex-distr.pdf]]

#+NAME: fig:umbr-hex-change
#+BEGIN_SRC R :results output graphics :file fig/umbr-hex-change.pdf :width 4.5 :height 2
  hex.diffs <- merge(subset(hex.rates, Year==2001),
                     subset(hex.rates, Year==2013),
                     by="hex.id", suffixes=c(".01", ".13"))
  hex.d.toplot <- merge(base.hex, hex.diffs, by.x="id", by.y="hex.id")
  hex.d.toplot <- hex.d.toplot[order(hex.d.toplot$id, hex.d.toplot$order),]

  chg.min <- min(hex.d.toplot$UMBR.13 - hex.d.toplot$UMBR.01)
  chg.max <- max(hex.d.toplot$UMBR.13 - hex.d.toplot$UMBR.01)
                                          # chg.min is roughly double chg.max

  colpal.unbalanced <- c(dark.blue, blue, grey.1, red.2)
  colpal.breaks <- rescale(c(chg.min, mean(chg.min,0), 0, chg.max))

  ggplot(data=hex.d.toplot, aes(x=long, y=lat, group=group)) +
      geom_polygon(aes(fill=UMBR.13-UMBR.01), alpha=1) +
      scale_fill_gradientn("UMBR change\n2001-13",
                           colours=colpal.unbalanced,
                           values=colpal.breaks,
                           labels=percent_format()) +
      la_overlay_thick + n2_overlay_thick +
      coord_equal() +
      the_map_theme_legend_right
#+END_SRC

#+LABEL: fig:umbr-hex-change
#+CAPTION[Map of changes in the UMBR poverty proxy rate 2001–2013]: Changes in the UMBR poverty proxy rate, showing the absolute difference between the 2001 and 2013 percentage rates. Drawn area sizes adjusted towards population size. The dark grey and white lines show the approximate outlines of the NUTS2 divisions and of individual boroughs respectively.
#+RESULTS[85c1ef08473567f5f001fa56804c8061d92bb8e2]: fig:umbr-hex-change
[[file:fig/umbr-hex-change.pdf]]

The maps also show, however, changes in the spatial distribution of poverty over the period. The poverty proxy rate fell sharply in the areas of its highest concentration in inner East London. As already remarked, this is consistent with observed trends in official deprivation indices[[cite:leeser_english_2011][;]], and corresponds to those areas that have received the greatest academic and media attention as "gentrifying" areas. In the same time period, poverty rates have risen in several parts of outer London, above all in those parts which started the period relatively deprived in comparison to outer London as a whole. This change is brought out clearly in figure \ref{fig:umbr-hex-change}. In the most-changed parts of inner London, UMBR rates fell by as much as 12 percentage points (for reference, the most deprived parts of inner East London having rates in 2001 in the range of 30 to 40). Inner West London, however, shows no overall change, with small falls in poverty in some areas and small rises in others.

#+NAME: fig:umbr-nuts-changes
#+BEGIN_SRC R :results output graphics :file fig/umbr-nuts3-changes.pdf :width 4.5 :height 2.5
  umbr.l.dt <- data.table(umbr.l)

  inout <- data.table(umbr.l)[,sum(All.MTB, na.rm=TRUE) /
                                  sum(Hholds, na.rm=TRUE),
                              by=c("Year","NUTS2")]
  inout$NUTS2 <- gsub(" - ", "\n", inout$NUTS2)

  my.nuts.pal <- c(dark.blue, red.3, blue, grey.2, red.2)
  ggplot(inout, aes(x=Year, y=V1)) +
  geom_line(aes(colour=NUTS2), linetype=1, size=1) +
  geom_smooth(method="lm", aes(colour=NUTS2),
              se=FALSE, linetype=3, size=1) +
  scale_colour_manual("", values=my.nuts.pal) +
  labs(x="Year", y="UMBR") +
  theme(legend.position="right")
#+END_SRC

#+LABEL: fig:umbr-nuts-changes
#+CAPTION[UMBR rates by NUTS2 areas, 2001 to 2013]: UMBR aggregate rates by NUTS2 areas, 2001 to 2013. The dotted lines show the simple regression trend for each area over the period.
#+RESULTS[4af4cabacdd1f494a43e7b9a97ff848d6d07bb78]: fig:umbr-nuts-changes
[[file:fig/umbr-nuts3-changes.pdf]]

City-wide underlying trends are shown in figure \ref{fig:umbr-nuts-changes}, which charts the aggregate UMBR rate for the five NUTS2 areas over the 2000s. Inner East London saw sharply falling poverty rates, whilst all three Outer London areas had rising poverty. Overall, inner and outer East London appear to be rapidly converging. The effects of the recession show up here as a rise in the poverty rate (primarily due to increases in the number of Job-Seeker's Allowance claims). This rise was greater in outer London, and the recovery from it slower; in all three outer London areas, the benefit-based proxy had not, by 2013, reached its pre-recession low.
** Population growth, densification and housing value
   It is important to note that in many of the poorest neighbourhoods of inner London, the UMBR rate decreased not primarily because the absolute number of poor people (the numerator of the UMBR rate) fell, but because the total number of households in the area (the denominator of the UMBR rate) rapidly rose. There is a consistent relationship between dwelling density, poverty, and increase in population over the period. The poorest neighbourhoods in 2001 were those then most densely built-up with dwellings. These same dense, poor, inner London neighbourhoods were subject to the greatest increases in dwelling density through net additions to the dwelling stock. The net upward change in total household population in these areas was much greater than any growth in the poor population, as measured by UMBR.

   In the relatively deprived neighbourhoods of Outer London by contrast, increases in the poor population were of similar size to the increases in the household totals, and poverty rates rose. As figure \ref{fig:household-increase} shows, few parts of Outer London experienced anything like the intensity of development and net additions to the household population. The most intense development of housing occurred in the former Docklands, and in parts of Tower Hamlets, Hackney and Islington, that is, surrounding the two main financial districts of London, the City and the Docklands.

#+NAME: fig:household-increase
#+BEGIN_SRC R :results output graphics :file fig/umbr-households.pdf :width 4.5 :height 2
  chg.min <- min(hex.d.toplot$Hholds.13 / hex.d.toplot$Hholds.01 - 1)
  chg.max <- max(hex.d.toplot$Hholds.13 / hex.d.toplot$Hholds.01 - 1)

  ggplot(data=hex.d.toplot, aes(x=long, y=lat, group=group)) +
      geom_polygon(aes(fill=Hholds.13/Hholds.01-1), alpha=1) +
      scale_fill_gradientn("Households % increase",
                           colours=colpal.diverging,
                           values=rescale(c(chg.min, 0, chg.max))) +
      la_overlay_thick + n2_overlay_thick +
      coord_equal() +
      the_map_theme_legend_right
#+END_SRC

#+LABEL: fig:household-increase
#+CAPTION[Map of household growth 2001-2013]: Proportional change in the total number of households 2001 to 2013, based on the UMBR dataset. Drawn area sizes adjusted towards population size. The dark grey and white lines show the approximate outlines of the NUTS2 divisions and of individual boroughs respectively.
#+RESULTS[8978138795b67210ec616706e11c2ddd9e4139d1]: fig:household-increase
[[file:fig/umbr-households.pdf]]

Furthermore, this housing, as with that of developments further west on the river Thames, was of high value relative to what stood there at the start of the period under study. Figure \ref{fig:dwelling-value-change} uses Council Tax banding information to show this upward shift in mean values in inner East London and along the riverside. Council Tax bandings are preferred here to market-sale prices as a measure of dwelling value because they are assessed from the notional price at a fixed point in time, thus making values comparable without need to adjust for overall house price inflation. Thus the shifts in mean value here reflect only the effects of demolitions and additions to the housing stock: what kind of housing was built, and what kind of housing was removed.

#+NAME: fig:dwelling-value-change
#+BEGIN_SRC R :results output graphics :file fig/dwell-value.pdf :width 4.5 :height 2
  dw.01 <- read.delim("data/lnd-ctax_band-lsoa-2001.tab", skip=5)
  dw.01 <- dw.01[,c(1:10, 13, 14, 16, 18, 20, 22, 24, 26, 28, 30)]
  colnames(dw.01)[11:20] = c("All", LETTERS[1:8], "X")
  dw.01$value.tot <- apply(dw.01[,LETTERS[1:8]], 1,
                           function(x) sum(x * 1:8) )
  dw.01$mean.band <- apply(dw.01[,LETTERS[1:8]], 1,
                           function(x) sum(x * 1:8) / sum(x) )

  dw.11 <- read.delim("data/lnd-ctax_band-lsoa-2011.tab", skip=5)
  dw.11 = dw.11[,c(11, 15, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34)]
  colnames(dw.11)[2:12] = c("All", LETTERS[1:8], "I", "X")
  dw.11$value.tot <- apply(dw.11[,LETTERS[1:8]], 1,
                           function(x) sum(x * 1:8) )
  dw.11$mean.band <- apply(dw.11[,LETTERS[1:8]], 1,
                           function(x) sum(x * 1:8) / sum(x) )

  dw <- merge(dw.01, dw.11, by="LSOA_CODE",
              all.y=FALSE, suffixes=c(".01", ".11"))
  hex.01 <- read.csv("hex_map_outlines/hex_lsoa01_memberships.csv")
  dw.hex <- merge(dw, hex.01, by.x="LSOA_CODE", by.y="LSOA01CD")
  hex.tots <- aggregate(cbind(All.01, All.11,
                              value.tot.01, value.tot.11)~hex.id, dw.hex, sum)

  hex.tots$mean.value.01 <- with(hex.tots, value.tot.01/All.01)
  hex.tots$mean.value.11 <- with(hex.tots, value.tot.11/All.11)
  hex.tots$value.change <- with(hex.tots, mean.value.11 - mean.value.01)

  hx.to.plot <- merge(hex.tots, base.hex, by.x="hex.id", by.y="id")
  hx.to.plot <- hx.to.plot[order(hx.to.plot$hex.id, hx.to.plot$order),]

  ggplot(data=hx.to.plot, aes(x=long, y=lat, group=group)) +
      geom_polygon(aes(fill=value.change), alpha=1) +
      scale_fill_gradientn("Mean Tax Band shift",
                           colours=colpal.diverging) +
      la_overlay_thick + n2_overlay_thick +
      coord_equal() +
      the_map_theme_legend_right
#+END_SRC

#+LABEL: fig:dwelling-value-change
#+CAPTION[Map of shift in mean dwelling value, 2001 to 2011]: Shift in mean dwelling value, based on Council Tax records, 2001 to 2011. Drawn area sizes adjusted towards population size. The dark grey and white lines show the approximate outlines of the NUTS2 divisions and of individual boroughs respectively.
#+RESULTS[5fa03bcbeabbe117a22813987f0d13e714190300]: fig:dwelling-value-change
[[file:fig/dwell-value.pdf]]

These initial results using a poverty proxy measure at neighbourhood level suggest that poverty rates fell with considerable speed across broad parts of inner East London in the 2000s. This was most pronounced in those areas where poverty was at the start of the period highest. In so far as we take falling poverty rates to be an index of gentrification, this indicates that gentrification proceeded apace across a broad sweep of inner London. The finding is somewhat at odds with the conclusions drawn by others on the basis of occupational class data, that there was "local gentrification" but "broad stability" [[cite:manley_london:_2014][;]]. This points to the need to cross-check the results from the poverty proxy with other sources, UMBR being especially sensitive to out-of-work poverty, and to look more closely at the composition of poverty in regards to economic activity. It also indicates the difficulty of judging what is "stability", and what ought to be deemed "slow" or "rapid" change. All of these points are taken up in the section which immediately follows and again in the concluding discussion.

The population and housing data show the clear connection in the case of inner East London between the pattern of housing development and falls in poverty rates. These falls were the result of increasingly dense settlement and development, and were accompanied by marked upward movement in the total and average value of housing capital. This was evident above all in Tower Hamlets. The development of such areas was explicitly foreseen in planning documents, and happened on sites that "evince that mix of relative deprivation and development potential which promises a substantial uplift in value, given the right catalytic boost." [[cite:keddie_market_2010][p.58;]]. The contribution of net additional housing and population growth to reducing poverty rates — but not numbers — confirms the relevance of the academic debate, touched on in the introduction, on "new-build gentrification" [[cite:davidson_new-build_2010][;]]. However, it should be noted that the preceding analysis only shows /net/ additions; it does not reveal what proportion were built on formerly industrial or commercial land, and what proportion on sites where existing lower-value and often public housing was first demolished. The dwelling stock data used offers further opportunities to investigate this question, but this lies beyond the central argument of this paper.

However, the trends across the city as a whole suggest that the role of new-build housing ought not to be overstated[fn:8]. In much of inner West London, poverty rates also fell, albeit more slowly and from a lower base than in inner East. This occurred without the rapid new development and, riverside sites aside, the upward movement in mean housing base value (market prices, of course, increased rapidly). In much of the relatively prosperous parts of Outer London, the analysis of poverty rates does confirm a picture of "broad stability" rather than rapid change. Nonetheless, the poverty proxy data suggests that many relatively disadvantaged parts of Outer London saw increases in poverty rates, in boroughs on the administrative boundaries of the city such as Enfield, Hillingdon and Croydon. To develop the interpretation of these complex and varying findings, we now proceed to the results of the spatial microsimulation exercise.
* The Changing Structure of Poverty
  The remaining results presented in this paper come from borough-level income and poverty simulations using /Households Below Average Income/ and census data. The simulations employ a standard notion of reported income from all sources (earnings, benefits, investments), which is deemed shared within a benefit unit (roughly, a family), adjusted for the number of adults and children who live on that income, and measured after housing costs have been deducted in order to give a residual income available for consumption. A person is defined as poor when the benefit unit of which they are a member has such an income which is less than 60% of the national median[fn:4]. These simulations imply London-wide poverty rates and income distributions that are consistent with those derived directly from HBAI[fn:1].

  The purpose of this analysis is first to confirm the spatial trends found in the analysis of the UMBR poverty proxy using this conventional income-based poverty definition rather than the administrative one implicit in UMBR. Confirming the trends, broadly of falling poverty in parts of inner London and rising poverty in part of outer London, should provide supporting evidence of the scale and extent of gentrification in the period of interest. Further, the simulation data will allow us to examine the composition of poverty. Specifically, we will be interested in changes in the relative distribution of in-work and out-of work poverty, only the latter of which is directly observed in the UMBR measure. 

  Before pursuing this analysis, it ought briefly to be noted that the spatial microsimulations compare two snapshots in time. Since the estimation method relies on population census data, the time periods compared are, as described above, 2001 (using 2001 Census data and HBAI 2001/02) and 2011 (using that year's Census and HBAI 2011/12). The changes in borough poverty rates and income that are now presented reflect a wide variety of effects over this decade, including the movement of people, the changing circumstances of households, altered tax and benefit regimes, conditions in the labour market, and changes to the housing stock. 

  As background information, median real income AHC rose in London from 2001/02 up until 2007/08, but then fell back sharply, such that it was no higher at the end of the period than the start[fn:3]. Mean real income, which, unlike the median, is influenced by the values of top incomes, in fact fell over the decade as a whole. Changes in borough median income plotted in figure \ref{fig:median-income-change} nicely illustrate the net effects of the period of growth and the first years of the recession. Median incomes in the poorest boroughs were flat over the decade, whilst median incomes fell more sharply in more wealthy boroughs[fn:5]. The lowest-income boroughs in inner London had the lowest shares of household income deriving from earnings, whilst income from benefits was relatively protected against inflation in the early pre-coalition phase of the recession. CASE's more recent and shorter-run analysis from 2007/08 to 2012/13, however, shows that in London, falls in income were proportionally greatest in the bottom half of the income distribution[[cite:vizard_changing_2015][p.13;see]]; the concluding discussion takes up the question of possible trends after the period for which data are reported here.
#+NAME: setup-simulations
#+BEGIN_SRC R :exports none :results silent
  setwd("../ipf")

  # Load the HBAI datasets
  if ( ! exists("hbai.01.ln") ) {
      source("frs_2001-load_recode.r")
      hbai.01.ln <- subset(hbai, GVTREGN==8)
  }
  if ( ! exists("hbai.11.ln") ) {
      source("frs_2011-load_recode.r")
      hbai.11.ln <- subset(hbai, GVTREGN==8)
  }

  # Some variable definitions
  tenures <- c(rep("Soc Rent",2),rep("Pvt Rent", 2),
               rep("Own", 2), "Pvt Rent")
  hbai.01.ln$tenure.3 <- tenures[hbai.01.ln$TENTYPE]
  hbai.11.ln$tenure.3 <- tenures[hbai.11.ln$PTENTYP2]


  working <- c(rep("Working",5), "Not Wkg Age",
               rep("Workless",2))
  hbai.01.ln$workless.bu <- working[hbai.01.ln$ECOBU]
  hbai.11.ln$workless.bu <- working[hbai.11.ln$ECOBU]

  # Sims to count number of benefit units and people, whole population
  if ( ! exists("nonexistent") ) { # Always remake
      newts.01 <- read.csv("../ipf/weights/london_la_2001-multilev_with_stwts.csv",
                           row.names=1)

      colnames(newts.01) <- gsub("\\.", " ", colnames(newts.01))
      sims.01.bu <- area.simulations(newts.01, hbai.01.ln, "SERNUM")
      sims.01.ppl <- area.simulations(newts.01, hbai.01.ln, "SERNUM",
                                      with(hbai.01.ln, G_NEWPP / G_NEWBU) )
      # Poor households only
      hbai.01.poor <- subset(hbai.01.ln, LOW60AHC==1)
      pov.sim.01 <- area.simulations(newts.01, hbai.01.poor, "SERNUM",
                                     with(hbai.01.poor, G_NEWPP / G_NEWBU))
  }

  if ( ! exists("nonexistent") ) { # Always remake
      newts.11 <- read.csv("../ipf/weights/london_la_2011-multilev_with_stwts.csv",
                           row.names=1)
      colnames(newts.11) <- gsub("\\.", " ", colnames(newts.11))
      sims.11.bu <- area.simulations(newts.11, hbai.11.ln, "SERNUM")
      sims.11.ppl <- area.simulations(newts.11, hbai.11.ln, "SERNUM",
                                      with(hbai.11.ln, G_NEWPP / G_NEWBU) )
      # For looking at the composition of poor households
      hbai.11.poor <- subset(hbai.11.ln, LOW60AHC==1)
      pov.sim.11 <- area.simulations(newts.11, hbai.11.poor, "SERNUM",
                                     with(hbai.11.poor, G_NEWPP / G_NEWBU))
  }

  setwd("../paper")


  # Helper function for packing out borough-by-NUTS2 charts so that they look nice and griddy. Expects a standared melted data.frame with two id.vars representing the upper (NUTS2) and lower (LA) levels. Pads out with empty rows so that there are an identical number of lower levels per upper level.
  pad.with.stuff <- function(df, upper.group, lower.group,
                             dummy.value=0) {
      out.df <- df
      members <- tapply(df[,lower.group], df[,upper.group],
                        function(l) length(unique(l)))
      for ( u.grp in names(members) ) {
          pad.len <- max(members) - members[[u.grp]]
          if ( pad.len == 0 )  { next }
          pad <- data.frame(variable=df[,"variable"][1],
                            value=rep(dummy.value, pad.len))
          pad[,upper.group] <- u.grp
          # Use non-breaking space because it sorts after alphabet
          pad[,lower.group] <- sapply(1:pad.len,
                                      function(i) paste(rep(" ", i),
                                                        collapse=""))
          out.df <- rbind(out.df, pad)
      }
      out.df
  }
#+END_SRC

#+NAME: fig:median-income-change
#+BEGIN_SRC R  :results output graphics :file fig/income_change-boroughs-2001_11.pdf :width 4.5 :height 3.5
  deflators.bhc <- c("2001"=172.9, "2011"=234.7)
  deflators.ahc <- c("2001"=164.5, "2011"=222.0)

  mds <- merge(area.sim.quantiles(sims.01.ppl, ~S_OE_AHC),
               area.sim.quantiles(sims.11.ppl, ~S_OE_AHC),
               by=0, suffixes=c(".01", ".11") )
  mds$Y2001.median.inflated <- mds[,"0.5.01"] * deflators.ahc["2011"] / deflators.ahc["2001"]
  mds$Y2011.median <- mds[,"0.5.11"]

  ## area.sim.means(sims.01.bu, ~S_OE_AHC)
  ## area.sim.means(sims.11.bu, ~S_OE_AHC)

  # Earned vs total net income
  earn.comp <- do.call(rbind, lapply(sims.01.bu, svytotal,
                                     x=~ENTERNBU+HNTINCBU))
  mds$earn.prop <- earn.comp[,1] / rowSums(earn.comp)

  mds.with.codes <- merge(mds, borough.defs, by.x="Row.names", by.y="LA.NAME")

  ggplot(mds.with.codes, aes(x=Y2001.median.inflated,
                  y=Y2011.median,
                  colour=earn.prop,
                  shape=InOutLondon)) +
      geom_abline(aes(slope=1), linetype=3, intercept=1) +
      geom_point() +
      scale_x_continuous("2001 Income  (equivalised, AHC, 2011/12 prices)") +
      scale_y_continuous("2011 Income (equivalised, AHC)") +
      scale_colour_gradientn("Prop. net income\nfrom earnings, 2001",
                             colours=colpal.diverging) +
      scale_shape_manual("", values=c(16,15)) +
      coord_equal()
#+END_SRC

#+LABEL: fig:median-income-change
#+CAPTION[Borough estimated real median incomes, 2001 and 2011]: Borough real median incomes (AHC, equivalised), 2001 and 2011, in 2011/12 prices. Points are shaded according to the proportion of net household income derived from earnings in 2001.
#+RESULTS[982b9867e2490511ac28f0e906f0301ffa0d4962]: fig:median-income-change
[[file:fig/income_change-boroughs-2001_11.pdf]]
** Poverty change by district
   Reprising the analysis above of the changing spatial distribution of poverty, figure \ref{fig:pov-change-boroughs} charts boroughs' poverty rates based on the 2001 simulation against their rate in 2011. Against the background of a London-wide poverty rate that was almost unchanged, boroughs below and right of the dotted line had falling poverty rates, boroughs above and to the left, rising. This provides confirmation of the analysis of the UMBR poverty proxy measure. The poorest boroughs in both 2001 and 2011 were in inner East London, successively Newham, Tower Hamlet and Hackney, each of which had poverty rates of greater than 40%. However, poverty rates fell in all inner East boroughs, most markedly in Islington (by 9 percentage points) and Hackney (by 7).

#+NAME: fig:pov-change-boroughs
#+BEGIN_SRC R :exports results :results output graphics :file fig/pov_change-boroughs-2001_11.pdf :width 4.5 :height 3
  pov <- merge(area.sim.table(sims.01.ppl, ~LOW60AHC),
               area.sim.table(sims.11.ppl, ~LOW60AHC),
               by=0, suffixes=c(".01",".11"))

  pov$pov.01 <- pov[,3] / rowSums(pov[,2:3])
  pov$pov.11 <- pov[,5] / rowSums(pov[,4:5])

  pov <- merge(pov, borough.defs, by.x="Row.names", by.y="LA.NAME")
  pov$NUTS2 <- factor(pov$NUTS2,
                      levels = c("Inner - East",
                          "Outer - East & NE",
                          "Outer - South",
                          "Inner - West",
                          "Outer - West & NW") )

  # Label selected boroughs
  interesting.boroughs <- c("Newham", "Hackney", "Tower Hamlets", "Islington",
                            "Enfield", "Croydon", "Hillingdon", "Camden",
                            "Brent", "Greenwich", "Kingston upon Thames",
                            "Haringey", "Westminster", "Ealing")
  pov$label <- ifelse(pov$Row.names %in% interesting.boroughs,
                      pov$LA.ABBR3, "")

  my.nuts.pal <- c(dark.blue, red.3, blue, grey.2, red.2)
  ggplot(pov, aes(x=pov.01, y=pov.11) ) +
      geom_abline(intercept=0, slope=1, linetype=3) +
      geom_point(aes(colour=NUTS215NM)) +
      geom_text(aes(label=label), size=2, hjust=-0.2) +
      scale_x_continuous("Poverty rate (people, AHC) 2001",
                         limits=c(0.15, 0.5)) +
      scale_y_continuous("Poverty rate (people, AHC) 2011",
                         limits=c(0.15, 0.5)) +
      scale_colour_manual(values=my.nuts.pal) +
      coord_equal() +
      facet_wrap(~NUTS2, ncol=3) +
      guides(colour=FALSE)
#+END_SRC

#+LABEL: fig:pov-change-boroughs
#+CAPTION[Change in borough poverty rates, 2001 to 2011]: Change in estimated income poverty rates (<60% national median income, equivalised after housing costs) by borough, 2001 to 2011.
#+RESULTS[b55f83452ac8fc16158605b3855fafb13dffd50d]: fig:pov-change-boroughs
[[file:fig/pov_change-boroughs-2001_11.pdf]]

By contrast, poverty rates rose in all of the boroughs in West and South outer London, and rose the most in the boroughs such as Croydon (South London, +5%), Kingston-upon-Thames (South-West, +7%) Hillingdon (West, +9%) and Enfield (North, +6%). The microsimulation results confirm the broad pattern of spatial redistribution found in the proxy analysis, and indicate that the relative position of some boroughs has changed considerably. Table \ref{tab:nuts3-pov-rates} summarises the position by NUTS2 areas in 2001 and 2011, and can be compared to figure \ref{fig:umbr-nuts-changes}, above. It also shows poverty shares: whereas in 2001, inner and outer London had nearly even shares of the poor population (with inner London having a smaller population), the balance had shifted by 2011 decisively to outer London (58% in outer vs 42% in inner).
#+NAME: tab:nuts3-pov-rates
#+BEGIN_SRC R :exports results :results output latex
  pov.counts <- c("NP.01", "P.01", "NP.11", "P.11")
  colnames(pov)[1] <- "la"
  colnames(pov)[2:5] <- pov.counts

  pov.n3 <- aggregate(cbind(NP.01,P.01,NP.11,P.11)~NUTS2, pov, sum)
  pov.n2 <- aggregate(cbind(NP.01,P.01,NP.11,P.11)~InOutLondon, pov, sum)
  names(pov.n3)[1] <- names(pov.n2)[1] <- "Area"

  pov.nuts <- with(rbind(pov.n2[order(as.character(pov.n2[,1])),],
                         pov.n3[order(as.character(pov.n3[,1])),]),
                   data.frame(row.names=Area,
                              pov.rate.01=P.01/(NP.01+P.01),
                              pov.rate.11=P.11/(NP.11+P.11),
                              pov.share.01=P.01/sum(P.01)*2,
                              pov.share.11=P.11/sum(P.11)*2 ) )

  latex.glove(pov.nuts,
              caption="Estimated income poverty rates (people) and shares of all people in poverty in NUTS areas of London, 2001 and 2011",
              caption.lot="Poverty rates and shares for NUTS areas of London, 2001 and 2011",
              label="tab:nuts3-pov-rates",
              title="Area",
              n.rgroup=c(2,2,3), rgroup=c("London", "Inner London", "Outer London"),
              n.cgroup=c(2,2), cgroup=c("Poverty Rate", "Poverty Share"),
              colheads=rep(c("2001", "2011"),2),
              digits=2)
#+END_SRC

There are, however, some differences between the two sources in both the scale of changes and their relative extent in different parts of the city. One key difference to the UMBR results is that poverty rates here appeared to rise the most in outer West and South London, rather than in outer East. The following disaggregations of the poverty rate help to account for this difference.
** Poverty by economic status
   One of the most marked changes in the structure of poverty in Britain over the 2000s was the sharply increased proportion of the poor who are poor despite there being an adult in work in the household[fn:6]. This development was especially pronounced in London: "[a] decade ago, the majority of children and adults in poverty in London were in workless families (55%); now the majority live in a family where someone is in work (60%)" [[cite:aldridge_londons_2015][p.25;]]. The spatial microsimulation estimates allow us to look at how this has affected different boroughs within the city. Figure \ref{fig:economic-status-borough} gives a decomposition of the effects of this shift by borough. It shows the net change in the number of the poor in each borough, according to whether the benfit unit in which they live has any person in employment. State income support to low-income pensioners increased substantially over the period, and therefore benefit units where no-one is working but where the head of the unit or their spouse is aged over 60 are separated out and shown in a separate column.

#+NAME: fig:economic-status-borough
#+BEGIN_SRC R :exports results :results output graphics :file fig/econstat_borough.pdf :width 4.5 :height 6.5
  ecstat.01 <- area.sim.table(pov.sim.01, ~ECOBU)
  ecstat.11 <- area.sim.table(pov.sim.11, ~ECOBU)

  wkls.01 <- data.frame(workful=rowSums(ecstat.01[,1:5]),
                        pens=ecstat.01[,6],
                        workless=rowSums(ecstat.01[,7:8]))
  wkls.11 <- data.frame(workful=rowSums(ecstat.11[,1:5]),
                        pens=ecstat.11[,6],
                        workless=rowSums(ecstat.11[,7:8]))

  wrk.cmp <- merge(wkls.01, wkls.11, by=0, suffixes=c("01", "11"))
  wrk.cmp <- merge(wrk.cmp, borough.defs, by.x="Row.names", by.y="LA.NAME")

  wrk.cmp$workful.chg <- wrk.cmp$workful11 - wrk.cmp$workful01
  wrk.cmp$workless.chg <- wrk.cmp$workless11 - wrk.cmp$workless01
  wrk.cmp$pens.chg <- wrk.cmp$pens11 - wrk.cmp$pens01

  foo <- melt(wrk.cmp, id.vars=c("LA.SHORTNAME", "NUTS2"),
              measure.vars=c("workful.chg", "workless.chg", "pens.chg") )
  foo.o <- pad.with.stuff(foo, "NUTS2", "LA.SHORTNAME", 0)

  ggplot(foo.o, aes(x=LA.SHORTNAME, group=variable, y=value/1000, fill=variable)) +
      geom_bar(stat="identity", position="dodge") +
      scale_x_discrete("") +
      scale_fill_manual("", values=colpal.qual,
                        labels=c("\"Working\"\n (head and/or spouse working)",
                                 "\"Workless\",\n head and spouse aged <60",
                                 "\"Workless\",\n head or spouse aged 60+")) +
      scale_y_continuous("People (thousands)") +
      facet_wrap(~NUTS2, scales="free_x", ncol=1) +
      theme(legend.position="bottom")
#+END_SRC

#+LABEL: fig:economic-status-borough
#+CAPTION[Borough change in poverty, by economic status of benefit unit]: Net change in total people in poverty, by economic status of benefit unit, by borough, 2001-2011.
#+RESULTS[d2a400a05e6d7373a32d84612f4dc453a81fb5d5]: fig:economic-status-borough
[[file:fig/econstat_borough.pdf]]

Apparent overall is the trend for out-of-work poverty to fall, and for in-work to increase. The balance between these tendencies is, however, very different from borough to borough. In gentrifying boroughs, notably Islington, Camden and Hackney, the absolute falls in workless poverty were greater than the rise in in-work poverty; this, combined with the increases in the size of the resident population, accounts for the sharp falls in poverty rates in these boroughs. In other parts of inner East London, such as Tower Hamlets, Newham and Southwark, increases in in-work poverty more than offset falling numbers out of work. The more modest falls in overall poverty rates in these boroughs are thus attributable to the growth in population, and smaller reductions in poverty among those above working age.

In the boroughs of outer London, falls in out-of-work poverty were small or negligible. Two of the most strongly "declining" boroughs, Enfield and Hillingdon, recorded small increases in the absolute numbers in out-of-work poverty. The major changes to poverty rates in outer London are the consequences not of changes in worklessness (the "underclass", in Wright's terms), but by very large increases in in-work poverty ("exploitation"). Rises in private housing costs, relative to the wages of lower-income workers, impoverished tens of thousands of households in these boroughs.

As before, these are comparisons of cross-sections at two time points, which do not allow us to attribute importance to the relative effects of local changes in labour markets, wages and housing costs, and population movement into and out of each borough. For the population above working age, the increased generosity of income transfers to retired people played a major role in the falling poverty counts recorded for this group in every borough. This cross-sectional analysis does make much clearer that it is not only the distribution of poverty, but its composition that has changed. Even in the most strongly gentrifying boroughs, rising in-work poverty has tempered the effects of falling worklessness, whilst in outer London, it has outweighed and magnified changes to worklessness in its contribution to rising overall income poverty.
** Poverty by housing tenure
   Gentrification in London in the 2000s was marked not, as in classic accounts, by the replacement of renting by owner-occupation, but by the rapid expansion of private renting. At the same time, social rented housing declined in share and importance as a means of providing housing to low-income households, whilst state subsidies to private rents through Local Housing Allowance (Housing Benefit) increased. Alongside this, the gap between poverty rates before and after housing costs grew ever wider, and the housing circumstances of the income-poor in different parts of the city are thus of particular interest.

#+NAME: fig:poverty-tenure-change
#+BEGIN_SRC R :exports results :results output graphics :file fig/pov_tenure_change.pdf :width 4.5 :height 6.5
  ten.cmp <- merge(area.sim.table(pov.sim.01, ~tenure.3),
                   area.sim.table(pov.sim.11, ~tenure.3),
                   by=0, suffixes=c(".01", ".11"))

  ten.cmp$sr.chg <- ten.cmp[,"Soc Rent.11"] - ten.cmp[,"Soc Rent.01"]
  ten.cmp$pr.chg <- ten.cmp[,"Pvt Rent.11"] - ten.cmp[,"Pvt Rent.01"]
  ten.cmp$oo.chg <- ten.cmp[,"Own.11"] - ten.cmp[,"Own.01"]

  ten.cmp <- merge(ten.cmp, borough.defs, by.x="Row.names", by.y="LA.NAME")

  # ten.cmp.0 <- melt(ten.cmp, id.vars=c("LA.SHORTNAME", "NUTS215NM", "LA.ABBR3"),
  ten.cmp.0 <- melt(ten.cmp, id.vars=c("LA.SHORTNAME", "NUTS215NM"),
                    measure.vars=c("sr.chg","pr.chg","oo.chg"))
  ten.cmp.0 <- pad.with.stuff(ten.cmp.0, "NUTS215NM", "LA.SHORTNAME")

  ggplot(ten.cmp.0,
         aes(x=LA.SHORTNAME, y=value/1000, group=variable, fill=variable)) +
         geom_bar(stat="identity", position="dodge") +
         scale_x_discrete("") +
         scale_y_continuous("People (thousands)") +
         scale_fill_manual("", labels=c("Social Rented", "Private Rented", "Owner Occupied"), values=colpal.qual) +
         facet_wrap(~NUTS215NM, ncol=1, scales="free_x")
#+END_SRC

#+LABEL: fig:poverty-tenure-change
#+CAPTION[Borough change in people in poverty, by housing tenure]: Net change in total people in poverty, by housing tenure, by boroughs 2001 to 2011.
#+RESULTS[b4f03985456c8f4c01fde1a7eb3052d7fc43fa21]: fig:poverty-tenure-change
[[file:fig/pov_tenure_change.pdf]]

Figure \ref{fig:poverty-tenure-change} presents the net absolute change in the population in poverty in each borough by housing tenure. The unambiguously gentrifying boroughs of inner East London again present a distinct pattern.  The numbers in low income in social housing fell — in some boroughs, like Southwark, because social housing was sold off or demolished in greater quantity than it was replaced — but also because the relative circumstances of social tenants somewhat improved. Social renting remained in 2011/12 
much the poorest housing tenure, but poverty rates fell; this is in part accounted for by the relatively large proportion of social tenants who are above retirement age and who thus benefited from the more generous income transfers just mentioned. In inner east London, the offsetting of falls in out-of-work poverty by rises in in-work poverty is mirrored in falls in poverty in social renting and rises in private renting.

Rates of poverty among private tenants and owner-occupiers increased London-wide. In the relatively declining boroughs of outer London, the increases in the population of low-income households has occurred entirely within private housing. This is again in part attributable to the rapid growth of the private rented sector, but also to the high proportion of private tenants - and in some cases, also owner-occupiers - on low incomes in these areas.
* Discussion
  It was already known that economic growth and physical development in London in the 2000s were accompanied by a rise in in-work poverty and, further, no decrease in the overall poverty rate. The data presented here show that whilst city-wide poverty rates hardly changed, there was a marked spatial redistribution of poverty in the city, from the inner city to the suburbs. As argued in the introduction, if income poverty is an indicator of class position, then this is evidence for gentrification occurring across inner East London.

  In itself this may not be an especially surprising or novel conclusion. What the analysis adds is firstly a new view of extent and speed. As noted above, cross-Census analysis using occupational class categories has pointed to overall stability and evidence of local gentrification between 2001 and 2011. Some popular media representations of gentrification, in focusing on the most egregious cultural and economic contrasts between new and existing residents, tend to convey a view of gentrification as occurring in "hotspots". The quantitative analysis presented above suggests, in contrast, that changes in socio-economic composition consistent with gentrification were taking place across broad swathes of the inner city.

  As well as this revised appreciation of extent, the data offer a new perspective on the speed of socio-spatial change, which is inherently a matter involving a degree of judgement. If one is prepared to accept the changing spatial distribution of poverty as a yardstick of gentrification, how might one judge the magnitude of the changes over a decade from the material presented? After all, parts of London now often thought of as little blemished by deprivation — Chelsea, the West End or Notting Hill — were, in recent decades, thought thoroughly disreputable. From the present data, granted, the relativities of poverty rates at the scale of boroughs and wide zones of the city have not within a decade been upturned. Inner east London, and the boroughs of Newham and Tower Hamlets foremost within it, were at the end of the period the poorest in London, just as they were at the start.

  I would argue, however, that the net impression is of change of unusual rapidity. To give just a couple of examples: Islington, which featured in the England-wide "top five" of deprivation extent and rank in the 2004 Indices of Multiple Deprivation, now has a poverty rate lower than outer boroughs like Enfield, Redbridge, Hillingdon and Croydon, which did not appear in the top 50 [[cite:noble_english_2004][p.103ff;]]. The 2011 poverty rate in Brent is now similar to that in Hackney, which has consistently been identified by deprivation indices as one of the most deprived local authorities in England. Such changes over a decade in the relative position of larger spatial aggregates like boroughs are really quite rare in recent British economic geography. The relative positions of deprived districts in the Midlands and North have changed little over recent decades [[cite:gill_english_2015][pp.14-15;see for example]], with the most recent ups and downs of economic cycles if anything reinforcing these disparities [[cite:lee_grim_2012][;]].

  One of the consequences of the spatial redistribution of poverty in London is that it has effected the greater dispersion of poverty that, under the banner of "mixed communities", caught the eye of policy-makers and aroused the interest, skepticism, and sometimes ire, of researchers in the first decade of the 2000s [[cite:bond_mixed_2010][;]]. The convergence of poverty rates between inner and outer London, and falls in poverty in the highest-poverty neighbourhoods imply just the kind of deconcentration that was sought. Although the housing data show the spatial coincidence of housing development and re-development and falls in poverty, it is impossible to make an assessment of the contribution of explicitly "mixed communities" policies to the trends. Here, it is more important to underline that the convergence of poverty rates is not only a consequence of gentrification of the inner city, but of  proletarianisation in suburban areas.

  Other poverty reports have highlighted the worsening of a range of social and economic indicators in some outer London boroughs [[cite:aldridge_londons_2015][p.13;]]. The analysis in this paper shows, however, the striking divergence of trends in the composition of poverty. In inner London, the falls were in out-of-work poverty, the "oppressed" and "excluded", be that by displacement or absorption into paid labour. But in outer London it is the increase in in-work poverty, exploitation of labour, that accounts for the increases in poverty there. It reflects unequal and inequitable access to resources — most notably, housing — and work that does not provide a minimally adequate income. One attraction of using poverty measures as indices of gentrification in this way is that they connect directly back to the political-economic fields, such as labour and land, where poverty and inequality are produced. A valuable extension of the present work would be to look at the domestic level, that is, at how changes in household composition have varied between areas and how these have interacted with changes in aggregate poverty rates.

    As remarked at the outset, the trends took place against the backdrop of a period of rapid growth in aggregate prosperity  — financial crisis notwithstanding — and in the rate of value production in London as a whole. It is not novel to argue that London has high rates of poverty because of its prosperity, not (mysteriously) despite it: "[w]ithin the global city the dynamics of this particular form of growth produce poverty as well as wealth" [[cite:massey_world_2007][p.54-55;]]. Even so, the findings here confirm the need for distributional analysis that looks within regional disparities, and confirm that, at a city level, poverty reduction does not inevitably follow the accumulation of wealth.

    One unwanted side-effect of the material presented here is to heighten the imbalance of research attention given to London at the expense of other cities in the UK. It is not here assumed that the trends of inner gentrification and suburban proletarianisation are necessarily unique to London, a product of the city's exceptionalism as against the /RUK/ (Rest of the United Kingdom). In fact, an important question arising from the analysis is the degree to which the mode of urban development and its consequences for the spatial distribution of poverty reflect London's peculiarities as a world financial centre. Unfortunately in the UK, at least, comparative urban quantitative research is dominated by a concern with aggregate economic output, innovation and skills, in which the connection between city spatial structure and economic organisation remains relatively obscure. The methods used here could fruitfully be applied to other cities to make an initial assessment of gentrification trends outside London. Another promising direction in empirical research would be to make greater use of the latest Census interaction data on migration, to give at least a snapshot of the contribution of migration to the redistribution of poverty.

    Lastly, if one part of this paper's purpose has been to make the case for gentrification in London from 2001 and 2011 occurring at a wider extent and more rapidly than other analyses have suggested, it invites the question of what might be to come. Because of the limitations of available data, the picture presented is already at the time of writing three or more years out of date. In that time, even if the national economy does not appear to have returned to a stable phase of accumulation, development and speculation on inner London land and housing seems well "back on track". The changes observed in ten years already imply some re-evaluation of the relative position of whole boroughs. It does not take much imagination to project the rate of change seen in the last decade a further ten years forward (as the trend lines in figure \ref{fig:umbr-nuts-changes} rather crudely suggest), and to foresee a new urban distribution of poverty. Boroughs like Hackney and Tower Hamlets may well in the future have become "average", with the poor predominantly housed in the more peripheral, and currently less favoured, boroughs.

    This will depend not only on "market forces", but on recent and coming policy decisions and their consequences. The most consequential changes since the period under analysis are probably those made to welfare benefits, introduced by the last Coalition government since 2010, but many taking increasing effect only from 2012 or 2013. These are, on the one hand, a set of national changes to taxes and transfers whose effects are steeply regressive [[cite:browne_effect_2015][;]]. Since these apply the greatest proportional cuts to the already-poor, they may not of course, immediately change the spatial distribution of poverty in London, but will increase inequality of access to resources. Among these measures are however ones that have particularly severe implications for the poor in London, such as the — potentially shrinking — cap on total benefits, and caps and cuts to Local Housing Allowance [[cite:hamnett_moving_2010,fenton_housing_2011,aldridge_londons_2013]]. These measures will have affected precisely the poor who (still) live in the more expensive inner areas of London, who must "choose" between moving or remaning in yet more straitened circumstances. Occupational class data for the city as a whole may show that the "transformation of London from an industrial to a post-industrial city in terms of the shift in employment structure [might have] now almost run its course" [[cite:hamnett_changing_2015][p.245;]]. The material presented here suggests that the spatial consequences of changing class structure and class relations, as visible in gentrification, were and are still very much in progress.
* References
\printbibliography[heading=none]
* Footnotes

[fn:8] I am grateful to Rachel Aldridge and Antoine Paccoud for drawing my attention to this.

[fn:7] It should be noted that Wright's work of social class is very considerably more expansive and elaborated than the single aspect touched on here.

[fn:2] In 2015 the definition of NUTS areas in London was substantially revised. The former NUTS2 areas of Inner and Outer London were abolished, the five former NUTS3 areas were promoted to NUTS2 areas, and 21 new NUTS3 areas defined, each consisting of one or more boroughs. In this paper, Inner London refers to all the local authorities in the old "Inner" NUTS2 area: the City of London, Camden, Hammersmith and Fulham, Kensington and Chelsea,  Wandsworth and Westminster (Inner London West) plus Hackney, Haringey, Islington, Lambeth, Lewisham, Newham, Southwark and Tower Hamlets (Inner London East).

[fn:3] Table 2.5ts in the supplementary material to the HBAI analysis report gives the official median and mean average incomes by region, based on three-year rolling averages.

[fn:4] The appendices to the published HBAI reports give details of the definitions and procedures used in income measurement, see; [[cite:department_for_work_and_pensions_households_2014][;]].

[fn:5] The data point on the far right hand side with an extremely large fall in real median income is Kensington and Chelsea. Because of the particularly unusual composition of the borough, estimates of middle and higher incomes for it are subject to greater uncertainty than in other boroughs.

[fn:6] Table 3.5ts of HBAI's analysis report presents a time series. In 2001/02, 40% of low-income households had an adult in work; by 2011/12 this had reached 53%.

[fn:1] The simulation estimates have high uncertainty at the top of the income distribution, and in boroughs with many extremely high-income households.
