#+TITLE: Spatial microsimulation estimates of household income distributions in London boroughs, 2001 and 2011
#+AUTHOR: Alex Fenton
#+PROPERTY: header-args:R :session *R-LondonSimulation* :cache yes
#+PROPERTY: header-args :exports both
#+OPTIONS: toc:nil
#+LATEX_CLASS: generic-paper
#+LATEX_HEADER:\IfFileExists{secca-article.sty}{\usepackage{secca-article}}{}
#+LATEX_HEADER: \addbibresource{everything.bib}

#+BEGIN_abstract
Spatial microsimulation (SMS) is a range of techniques for estimating the local distribution of a variable – here, household income – by combining social survey microdata with Census or administrative population totals. The methods are attractive for social policy analysis of spatial economic differences. Unlike aggregate measures such as regional GVA and GDHI, they permit distributional analysis of income, and unlike local labour market indicators such as wages and employment rates, they encompass both market outcomes and secondary distribution through taxes and transfers. In comparison to deprivation indices and proxies, they measure income poverty and inequality in standard national terms. This paper presents an example of spatial microsimulation by iterative proportional fitting (IPF), in which the household income distribution in London's 33 boroughs in 2001/02 and 2011/12 is estimated. The coherence and plausibility of the results in comparison to other official statistics is examined in some details. Two refinements to standard IPF methods are presented. Multi-level IPF allows the use of both person- and household-level data; this is found to improve the estimation of poverty rates. Adjusting IPF starting weights by reference to personal tax data increases the dispersion of estimated distributions, but at the cost of increased error of estimates in wealthier areas. The paper confirms the value of SMS for synchronic spatial analysis, and for its hitherto little-explored use in modelling spatial differences in the effects of fiscal and welfare policy changes.
#+END_abstract

#+BEGIN_LaTeX
\clearpage
\section*{Acknowledgements}
This paper was developed from 2013 to 2015, whilst the author was a visiting fellow at CASE. The paper has benefited from exchanges with colleagues at the Centre over the years. Ben Anderson commented on an earlier draft of the paper, and offered many useful comments and suggestions. Any remaining errors are, of course, solely the author's responsibility.

The research used survey microdata from the Family Resources Survey and Households Below Average Income; access to these was provided by the UK Data Archive at the University of Essex. It also made use of 2001 and 2011 Census tables, provided by NOMIS. Additional administrative data used in the paper are provided by DWP (benefit claim statistics), HMRC (personal tax data), VOA (Council Tax data) and ONS (Regional Accounts). Crown Copyright on these materials is acknowledged as applicable.

The simulation and analysis of results was carried out in R statistics and made extensive use of several packages, including "survey", "ggplot2", "Hmisc". An online repository containing the IPF code, the resulting simulation weights, and the source for the analyses and figures presented in this paper is available online at *TODO*.


\clearpage
#+END_LaTeX

#+TOC: headlines 2
#+LATEX: \listoftables
#+LATEX: \listoffigures
#+LATEX: \clearpage

* Introduction
** Rationale
One feature of Britain's economic and social landscape is the existence of deep, persistent, and even growing spatial disparities in income and wealth between regions, cities and neighbourhoods. These disparities have been a recurring, if not constant, presence both in government policy and in research for much of the last century [[cite:ohara_journey_2005][;]]. Two broad disciplinary and practical traditions might crudely be distinguished within the field: /regional economics/, and the /geography of deprivation/. These traditions have their distinct vocabularies, methods and data sources, and have not always been in communication with one another.

An important strand of /regional economics/ describes, analyses and explains disparities between regions or between smaller spatial units. This includes analyses of differentials in output, wages or employment rates. The measures of economic well-being used in this work are, however, typically aggregates; they provide a single figure for each geographical unit of interest at each point in time. Seen through the lens of social policy, these approaches have the shortcoming that they do not consider the /distribution/ of the aggregate within each area[[cite:atkinson_monitoring_2015][;Compare]]. That is, an increase in Gross Disposable Household Income (GDHI) in an area need not correspond to any reduction in the proportion of households in poverty, if the aggregate increase is accompanied by an increase in inequality. Even analysis of wages, where sources such as the Annual Survey of Hours and Earnings (ASHE) permit some distributional analysis, looks only at the primary distribution of income, market outcomes. They take no account of the effects of the secondary distribution of income through taxes and transfers, nor of housing costs, on the final living standards of households. A policy which, through transfers, increased the proportion of households achieving a minimum consumption standard would, for example, not be reflected in wages data.

In the /geography of deprivation/ the focus has typically been upon smaller spatial units, often neighbourhoods. The characterisation and measurement of poverty and deprivation is the primary focus, rather than the relative wellbeing of the whole resident population. Key quantitative tools for such research are a variety of deprivation indices dating back to the 1970s. Earlier incarnations concentrated on the incidence of material deprivation, and used Census data; from the mid-1990s, indices have sought to characterise other domains of exclusion, such as sickness and crime, often through the addition of administrative data. Such indices have become widely used in policy circles and applied research, and can be adequate and useful proxies for the relative distribution of income deprivation[[cite:fenton_small-area_2013][;]]. They do, however, also detach small-area analysis of deprivation from the analysis of the whole income distribution, and, further, from the terms, techniques and measures in which low-income and inequality are addressed at national level. In addition, as a result of both welfare reform and rises in in-work poverty, the social security administrative data upon which present indices depend increasingly weakly identify the overall prevalence of low income[[cite:fenton_should_2013][;]]. This argument is acknowledged (and then dismissed), for example, in the government's response to the consulation on updating the English Indices of Deprivation [[cite:department_for_communities_and_local_government_updating_2015][pp18-19;]].

Spatial microsimulation (SMS) is a potential solution to at least some of these problems. SMS involves the synthesis of microdata from national household income surveys and local area population totals from censuses or administrative data. The outputs of SMS are effectively new datasets, which can be used to estimate income in the terms used in the specialised social surveys, but at the spatial level of districts or small-areas rather than national or regional data originally available. A wide variety of descriptive statistics can be calculated by SMS – not only means, but quantiles, poverty rates using thresholds, and measures of dispersion and inequality. Since the survey data separately measure income components, such as wages and transfers, SMS estimates likewise reflect both the primary and secondary distributions of income on household economic circumstances, and are sensitive to changes in transfers and taxation rates. The effects of housing costs on final income consumption are similarly incorporated.  Simulation results also permit a degree of sub-group analysis, such as, for example, the separation of in-work and out-of-work poverty, or the incidence of child poverty. For social policy analysis of poverty, SMS addresses criticisms of aggregate regional measures, that they do not have any necessary correlation with poverty, and of deprivation indices, that they poorly reflect in-work poverty.

Non-spatial simulations with survey data are used in Britain in both the Treasury (HMT) and the Department of Work and Pensions (DWP), as well as in research institutes like the Institute for Fiscal Studies (IFS)[[cite:edwards_developing_2009,roe_microsimulation_2009][;]]. These simulations model the effects of policy changes on households. /Spatial/ microsimulation techniques have, however, not thus far found widespread application in official statistics and analysis. The Department for Communies and Local Government (DCLG) commissioned a pilot project to examine using simulated income estimates within the English deprivation indices; this resulted in a very useful working paper [[cite:anderson_creating_2007][;]], but the actual results and resulting datasets were not made publicly available. Only in Northern 
Ireland are the results in the  public domain: [[cite:anderson_creating_2008][;]]. The Office for National Statistic's /Small Area Income Estimates/ are produced by econometric methods, discussed briefly below, which limit both the flexibility of the outputs and the reproduction and adaptation of the methods outside government. Since the decennial Census has not and likely will not measure income[[cite:office_for_national_statistics_2011_2005][;]], there remains a want of detailed and readily available sub-regional estimates of household income.

An exciting further possibility for policy research, which is however only lightly treated here, is using SMS results to simulate the local effects of national policy changes to taxes or benefits, effectively giving spatial disaggregation to the kind of modelling done by DWP, HMT and IFS. One could produce a simulation which presented to MPs the precise effects of proposed tax increases or benefit cuts in their constituency![fn:10] Finally, there may also be non-scientific reasons for microsimulation to enjoy a conjuncture. Microsimulation combines existing datasets rather than the demanding expensive new fieldwork, thus offering the promise of getting "more for less [[cite:haslett_more_2010][;]], in a period since 2010 in British official statistics where there has been a marked tendency to cut, rather than extend, primary fieldwork in social surveys. Britain may also be propitious territory for microsimulation given the reliance of the UK, as other anglo-saxon statistical systems, on social surveys[[cite:snorrason_peer_2015][;]]. The availability of relatively rich survey data and the absence (unlike in many nordic and continental European statistical systems) of population register data is well suited to the microsimulation approach.
** Outline and purpose of the paper
This paper presents a worked spatial microsimulation of household incomes for London boroughs in 2001/02 and 2011/12, with the hope that it might pique the interest of social policy researchers in the method. The paper considers a number of modest technical adaptations to the IPF fitting technique, which may be of interest to those already familiar with SMS. The paper's central focus is on the plausibility of the SMS results as estimates of the whole income distribution and lower and upper incomes. London is here a useful example, since there are found there high rates of poverty, marked inter-area differences, and the highest incomes in Britain. The differences between boroughs and over time are treated here, however, from a largely abstract and technical perspective. A companion paper, /Gentrification in London: a Progress Report 2001-2013/, takes up the interpretation of the results in spatial and policy context, and it will be more relevant for those with a primarily substantive interest in income and poverty in London.

The body of the paper first sets out more formally what SMS is, and how it differs from other small-area estimation approaches. The sources and techniques used are then described, including two refinements to microsimulation techniques which are new in the published UK literature. The largest part of the paper is an examination of the coherence of the results with other available sources, including published poverty measures, wages and benefits data.
* Spatial microsimulation and other methods
Spatial microsimulation combines social survey data with local Census or administrative data. The survey data – in this example, the /Family Resources Survey/ (FRS) and the derived dataset /Households Below Average Income/ (HBAI) – include the variables whose local distribution one ultimately wishes to estimate. In our case, these are the various detailed measures of gross, net and equivalised income contained in FRS. The local data are population totals (or "margins") for each area of interest, here 33 London boroughs, for a set of household and person characteristics that predict income, such as employment status, housing tenure and occupational class. The local data and survey cases are connected by a set of /link variables/, which are measured in the same way in both datasets: if the survey dataset measures employment status for each case using three categories, employed, unemployed and inactive, then the local data must provide area population totals for these same categories, identically derived.

With these two datasets to hand, the survey data are fitted, or constrained, to the local population margins in each borough successively. The weights of each survey case are adjusted until the weighted survey population resembles, as near as possible, the characteristics of the borough. Several distinct techniques exist to do this re-weighting of the survey cases to the local population totals, including generalised regression weighting and combinatorial optimisation [[cite:whitworth_evaluations_2013][p5ff;a useful summary is provided by]]. Here iterative proportional fitting (IPF) is used[[cite:anderson_estimating_2012][;]]. In IPF, the weights of each case are scaled arithmetically to each set of marginal totals constraint in turn, and this process then repeated a desired of times. This re-weighting is fundamentally the same process as that of 'calibration' in the literature of survey methodology, from where it was borrowed, and where IPF specifically is often termed 'raking'[[cite:lumley_analysis_2004][;]]. IPF is an arithmetically simple technique known since the 1950s, and is well described in the literature, with step-by-step illustrations; further elaboration is thus here foregone [[cite:ballas_geography_2005,simpson_combining_2005][;]].

The core of the microsimulation approach is thus the /linking variables/ which are, firstly, available in the survey data cases and as population totals for the areas of interest and, secondly, are predictors of the outcome variable of interest (income) in the survey source. Once the IPF has been carried out, one has a set of new weights, one for each survey case in each local area of interest. These new survey weights are then applied to the survey data to provide (weighted) estimates of the income and poverty statistics of interest for each local area.
** Other small-area income estimation methods
It is worth noting in passing that microsimulation is not the only method by which local income estimates can be derived through synthesis of local area and survey data. In recent years several reviews have compared microsimulation to other small-area estimation methods from both more theoretical and more practical standpoints [[cite:new_zealand_more_2010,whitworth_evaluations_2013,betti_poverty_2013][;Useful reviews include]]. This literature typically distinguishes a family of methods under the heading /spatial microsimulation/ from a set of approaches labelled /modelled/ or /statistical/.

These have in common some statistical method for combining the best available survey measure of income – in the UK, normally the /Family Resources Survey/ or /Understanding Society/ – with local area characteristics which predict inter-area variation in that income. Modelled or statistical approaches are so called because  a regression model is first fitted to the sample survey which estimates how some statistic of income, such as its mean, is related to local characteristics. Once a model has been fitted, the parameters are used to give predicted values for all areas from the local data. UK examples include Bramley's work on housing affordability [[cite:wilcox_evaluating_2010,bramley_modelling_1998][;]] and the Office of National Statistics' poverty estimates for  small areas [[cite:methodology_directorate_model-based_2010][;]], along with ONS's comparable earlier estimates of mean income. Parametric approaches – that is, those based on a formal specification of the statistical income distribution and estimation of its parameters - are also widely used in development economics[[cite:elbers_microlevel_2003][;A key paper here is]].

Aside from /modelled/ and /simulated/ approaches, one might also note the in applied statistics of /heuristic/ approaches, in which two or more data sources are synthesised or calibrated to produce local estimates, but with a technique not formally based on statistical theory. Such approaches apply judgement to the synthesis of multiple sources, translating, for example, observed variance in one dataset to predicted variance in another. The Greater London Assembly's suite of small-area income estimates  nicely exemplify this approach[[cite:gla_intelligence_gla_2014][;]].

To conclude the digression: there is not at present any decisive statistical criterion for choosing between modelling and simulation[fn:7]. In any case, modelled and simulated approaches have been argued to share an underlying model of the relationships among variables [[cite:haslett_more_2010][;]]. Preferences for one method or another are partly disciplinary: researchers with a  statistical science background tending to estimations based on distributions, econometrically oriented researchers preferring methods employing a predictive model of incomes in micro-data[[cite:methodology_directorate_model-based_2010][;e.g.]], and so on. The paper here takes a narrative and exemplifying approach to the method and concentrates not on the underlying model, but on the coherence and empirical plausibility of results in relation to their domain of intended application.
** Practical considerations
Despite this, there are some practical differences between modelling and simulation in the  estimates are produced. SMS by IPF is more exacting as to the form of local area data used, requiring that the constraints be totals for categorical variables, commonly defined and for the same units of observation as in the survey cases. Modelling can make free use of scalar or ratio data, and local predictors need not be variables directly relating to the survey units of observation. Modelled estimates can make use of administrative sources like benefit claim rates or house sale prices, which pose considerable problems of consistency and definition for SMS. It follows from this that IPF, in its basic form, considers only household-level variance in income; inter-area differences are modelled only as inter-area differences in population composition. In modelled estimates, inter-area differences in income can be conceived of as multi-level, including area area-level variables and efffects.

Modelled estimates however also demand that detailed spatial identifiers be available in the survey data, for the spatial units for which estimates are desired. In the UK context this is a significant hurdle, as access to survey microdata which identify the location of cases below regional level is, for sound reasons of respondent confidentiality, tightly controlled. Spatial microsimulation does not have this requirement, and thus can be carried out, as in this paper, from readily available public data sources; it does not require access to secured or commercial sources.

The other important practical difference between modelling and simulation lies in the form of the results produced. In modelled approaches, only a single statistic is modelled at one time, and correspondingly only a single statistic is estimated for each area. 
In the commonest models, this is mean income, and thus only area mean incomes are estimated. Logistic models might predict the probability of households being income poor, and thus estimate area proportions in income poverty; by means of quantile regression one can estimate medians and other points of local income distributions[[cite:tzavidis_m-quantile_2008][;]]. Each such specific income statistic which is wanted in the final results requires the specification of a separate regression model. By contrast, microsimulation weights, once generated in the re-weighting process, can be applied to the survey data to estimate,  with relative facility, multiple income statistics for each area, and can even be used to project or test policy changes. 
* Setup, Sources and Methods
#+NAME: setup-everything
#+BEGIN_SRC R :exports results :results output silent
  library(plyr)
  library(stringr)
  library(ggplot2)
  library(Hmisc)
  library(survey)
  library(scales)
  library(readr)
  library(reshape2)
  library(reldist) # Gini

  source("../r/ipf_functions.r")
  source("chart_style.r")
  # Borough definitions and table formatting help
  source("little_helpers.r")

  setwd("../ipf")
  # 2001 Data - FRS & HBAI
  if ( ! exists("ad.cons.01") ) {
    source("frs_2001-load_recode.r")
    frs.hh.01 <- subset(frs.hh, GVTREGN==8)
    frs.ad.01 <- subset(frs.ad, SERNUM %in% frs.hh.01$SERNUM)
    hbai.01 <- subset(hbai, GVTREGN==8)
    hbai.01$all <- 1
    hbai.01.svy.bu <- svydesign(id=~SERNUM+BENUNIT,
                                weights=~G_NEWBU,
                                data=hbai.01)
    # Household counts - only primary benefit unit
    hbai.hh.01 <- subset(hbai.01, BENUNIT==1)
    hbai.hh.01.svy <- svydesign(id=~SERNUM, weights=~G_NEWHH, data=hbai.hh.01)
    # Census data 2001
    source("constraints_2001.r")
    hh.cons.01 <- align.constraints(hhold.constraint.tables, frs.hh.01)
    ad.cons.01 <- align.constraints(adult.constraint.tables, frs.ad.01)
  }

  # 2011 Data - FRS & HBAI
  if ( ! exists("ad.cons.11") ) {
    source("frs_2011-load_recode.r")
    frs.hh.11 <- subset(frs.hh, GVTREGN==8)
    frs.ad.11 <- subset(frs.ad, SERNUM %in% frs.hh.11$SERNUM)
    hbai.11 <- subset(hbai, GVTREGN==8)
    hbai.11$all <- 1
    hbai.11.svy.bu <- svydesign(id=~SERNUM+BENUNIT,
                                weights=~G_NEWBU,
                                data=hbai.11)
    # Household counts - only primary benefit unit
    hbai.hh.11 <- subset(hbai.11, BENUNIT==1)
    hbai.hh.11.svy <- svydesign(id=~SERNUM,
                                weights=~G_NEWHH,
                                data=hbai.hh.11)
    # Census constraint data
    source("constraints_2011.r")
    hh.cons.11 <- align.constraints(hhold.constraint.tables, frs.hh.11)
    ad.cons.11 <- align.constraints(adult.constraint.tables, frs.ad.11)
  }

  # Set up a stack of different simulations
  # Wrapped in an "if" as a crude form of cache-ing  
  if ( ! exists("newts.11.sp") ) {
    # New weights 2001
    newts.01.sl <- read.csv("weights/london_la_2001-singlelevel.csv",
                            row.names=1)
    colnames(newts.01.sl) <- clean.la.colnames(newts.01.sl)
    sim.frsad.01.sl <- area.simulations(newts.01.sl, frs.ad.01, "SERNUM")
    sim.frshh.01.sl <- area.simulations(newts.01.sl, frs.hh.01, "SERNUM")
    sim.hbai.01.sl <- area.simulations(newts.01.sl, hbai.01, "SERNUM")

    newts.01.ml <- read.csv("weights/london_la_2001-multilevel.csv",
                            row.names=1)
    colnames(newts.01.ml) <- clean.la.colnames(newts.01.ml)
    sim.frsad.01.ml <- area.simulations(newts.01.ml, frs.ad.01, "SERNUM")
    sim.frshh.01.ml <- area.simulations(newts.01.ml, frs.hh.01, "SERNUM")
    sim.hbai.01.ml <- area.simulations(newts.01.ml, hbai.01, "SERNUM")
    newts.01.sp <- read.csv("weights/london_la_2001-multilev_with_stwts.csv",
                            row.names=1)
    colnames(newts.01.sp) <- clean.la.colnames(newts.01.sp)
    sim.frsad.01.sp <- area.simulations(newts.01.sp, frs.ad.01, "SERNUM")
    sim.frshh.01.sp <- area.simulations(newts.01.sp, frs.hh.01, "SERNUM")
    sim.hbai.01.sp <- area.simulations(newts.01.sp, hbai.01, "SERNUM")

    sim.hbai.01.sp.ppl <- area.simulations(newts.01.sp, hbai.01, "SERNUM",
                                           with(hbai.11, G_NEWPP / G_NEWBU))

    # New weights 2011
    newts.11.sl <- read.csv("weights/london_la_2011-singlelevel.csv",
                            row.names=1)
    colnames(newts.11.sl) <- clean.la.colnames(newts.11.sl)
    sim.frsad.11.sl <- area.simulations(newts.11.sl, frs.ad.11, "SERNUM")
    sim.frshh.11.sl <- area.simulations(newts.11.sl, frs.hh.11, "SERNUM")
    sim.hbai.11.sl <- area.simulations(newts.11.sl, hbai.11, "SERNUM")
    newts.11.ml <- read.csv("weights/london_la_2011-multilevel.csv",
                            row.names=1)
    colnames(newts.11.ml) <- clean.la.colnames(newts.11.ml)
    sim.frsad.11.ml <- area.simulations(newts.11.ml, frs.ad.11, "SERNUM")
    sim.frshh.11.ml <- area.simulations(newts.11.ml, frs.hh.11, "SERNUM")
    sim.hbai.11.ml <- area.simulations(newts.11.ml, hbai.11, "SERNUM")
    newts.11.sp <- read.csv("weights/london_la_2011-multilev_with_stwts.csv",
                            row.names=1)
    colnames(newts.11.sp) <- clean.la.colnames(newts.11.sp)
    sim.frsad.11.sp <- area.simulations(newts.11.sp, frs.ad.11, "SERNUM")
    sim.frshh.11.sp <- area.simulations(newts.11.sp, frs.hh.11, "SERNUM")
    sim.hbai.11.sp <- area.simulations(newts.11.sp, hbai.11, "SERNUM")

    # We need people weights to count poverty
    sim.hbai.11.sl.ppl <- area.simulations(newts.11.sl, hbai.11, "SERNUM",
                                           with(hbai.11, G_NEWPP / G_NEWBU))
    sim.hbai.11.ml.ppl <- area.simulations(newts.11.ml, hbai.11, "SERNUM",
                                           with(hbai.11, G_NEWPP / G_NEWBU))
    sim.hbai.11.sp.ppl <- area.simulations(newts.11.sp, hbai.11, "SERNUM",
                                           with(hbai.11, G_NEWPP / G_NEWBU))

    # Comparison simulations
    all.lond.cmp.01 <- data.frame(
      "HBAI" = hbai.01[match(row.names(newts.01.sl), hbai.01$SERNUM), "G_NEWHH"],
      "Household_Only" = rowSums(newts.01.sl),
      "Multi_Level" = rowSums(newts.01.sl),
      "SPI_Adjusted" =  rowSums(newts.01.sp),
      row.names = row.names(newts.01.sl) )
    sim.lond.01.cmp <- area.simulations(all.lond.cmp.01, hbai.hh.01, "SERNUM")

    all.lond.cmp.11 <- data.frame(
      "HBAI" = hbai.11[match(row.names(newts.11.sl), hbai.11$SERNUM), "G_NEWHH"],
      "Household_Only" = rowSums(newts.11.sl),
      "Multi_Level" = rowSums(newts.11.ml),
      "SPI_Adjusted" =  rowSums(newts.11.sp),
      row.names = row.names(newts.11.sl) )
    sim.lond.hh.11.cmp <- area.simulations(all.lond.cmp.11, hbai.hh.11, "SERNUM")
    sim.lond.bu.11.cmp <- area.simulations(all.lond.cmp.11, hbai.11, "SERNUM")
  }

  setwd("../paper")
#+END_SRC
** Linking variables
In the example here, SMS is used to estimate household income for the 33 boroughs (local authority areas) of London in the years 2001 and 2011. The survey source data is FRS and HBAI, and the local population data is taken primarily from the 2001 and 2011 UK Censuses of Population. This is supplemented with local administrative data on counts of dwellings by Council Tax Band; as discussed, other administrative data present problems of reconciling definitions and units of observation. 

The specific variables in the local population data are chosen on the strength of being predictors of household income in the survey data. The selection of income predictors by regression methods has been treated systematically and in depth by both Anderson [[cite:anderson_creating_2007][;]] and the ONS [[cite:methodology_directorate_model-based_2010][;]]. The present research drew on this work, and thus variable selection is not reported here in detail. The main differences in this paper is the use a set of variables common to both 2001 and 2011 datasets, and the possibility in the hierarchical fitting technique, described below, of using not only household-level but also adult-level Census and survey variables.

Table \ref{table-linkvars} summarises the linking variables used in the three variant simulations presented in this paper, the /Household-Only/, /Multi-Level/ and /SPI Prior-Weights/ simulations, which are shortly introduced. The variables are listed in reverse order in which the survey weights are adjusted to population totals, so that the variables listed first have, as it were, the highest priority. This simulated local area population totals for the last entered variable, household type, are thus always exactly correct. The source data, showing the derivation of the marginal constraints from census tables are available in the downloadable package accompanying this paper *TODO* [fn:8]. 

#+LABEL: table-linkvars
#+CAPTION: Variables used to link the Family Resources Survey with the Census 2001 and 2011
| *Sim/* | *Label*          | *Measurement* | *Description*                 |
| *Num*  |                  | *Level*       |                               |
|--------+------------------+---------------+-------------------------------|
| HHO/1  | HHOLD.TYPE       | Household     | Household composition         |
| HHO/2  | EMPLOY.STAT.HRP  | Household     | Household representative's    |
|        |                  |               | employment status             |
| HHO/3  | CTAX.BAND        | Household     | Council Tax Band of dwelling  |
| HHO/4  | TENURE           | Household     | Broad housing tenure          |
| HHO/5  | ACCOM.TYPE       | Household     | Type of dwelling              |
|--------+------------------+---------------+-------------------------------|
| MLV/1  | EMPSTAT.LIVARR   | Adult         | Employment status, by         |
|        |                  |               | whether living in a couple    |
| MLV/2  | NSSEC.ACTIVE     | Adult         | NS-SEC Occupational class     |
|        |                  |               | of economically active adults |
| MLV/3  | ETHNICITY        | Adult         | Broad ethnic group            |
| MLV/4  | AGE.SEX          | Adult         | Sex and 10-year age group     |
|--------+------------------+---------------+-------------------------------|
| SPI    | (Taxable Income) | Adult Tax     | Approximated distribution of  |
|        |                  | Payer         | taxable incomes (SPI)         |
|--------+------------------+---------------+-------------------------------|

It is worth noting that there are here some minor discrepancies between the survey data and the populations to which they refer. The local population total should be the sampling frame for the survey in that area. However, for example FRS is a sample of private households only, whereas some Census tables include people living in communal establishments such as care homes, student halls and prisons. Similarly, Council Tax Band (CTB) records cover all dwellings, but unoccupied dwellings are outside the FRS's sampling frame. These discrepancies are tolerated as being relatively small[fn:4] – indeed, CTB records are used in the FRS's own weighting scheme, despite the possible problems[[cite:lound_initial_2013][pp9,17;]]  – and are mitigated by ensuring that the highest-priority variables cover wholly corresponding populations.
** The Household-Only simulation /HHO/
The results in this paper derive from and compare three variants of the reweighting method. The first represents a standard IPF approach, and is referred to in the paper as the "Household-Only" (HHO) simulation, as it uses only household-level variables to link survey household cases with local population totals. In practice, this limits constraint variables to properties either of the household as a unit (its composition, number of children, tenure), of its dwelling (flat or house, tax band) or of its representative person (ethnicity, sex, age). The /HHO/ simulation uses only the five variables listed in the topmost section of  the linking variables in the reweighting procedure. It excludes some potentially useful household variables, notably number of earners per household, used in other work[[cite:anderson_creating_2007][;]], since the necessary local population totals have not been produced for the 2011 Census.
** The Multi-level simulation /MLV/
This restriction narrows the range of variables that might be used, since many Census totals are reported in more detail at the adult, rather than household, level. For example: in FRS, socio-economic class is reported only for economically active individuals, whereas the Census reports the NS-SEC of retired and unemployed people based on their last main job. Standard Census tables on class are thus not easily used as constraints as IPF, even though occupational class is, unsurprisingly, an important predictor of individual and household income. One must either, as Anderson does, make some judgement-based adjustment to the local totals of NS-SEC of household head [[cite:anderson_creating_2007][p10 fn2;]], or forego the use of this predictor altogether.

Furthermore, a household-level-only simulation will produce estimated local totals for individuals that are inconsistent with actual known totals. Thus, for example, the age/sex structure of the population or individual employment rates are not guaranteed to be correctly reproduced, because there are systematic inter-area differences in adult circumstances not observable in household-level variables (for example, rates of employment for married women). This means that a source of potential inter-area difference is missed, reducing the dispersion of the estimates, and also makes the weights less plausible for use in further policy simulation

The first refinement of IPF methods examined in this paper is thus a hierarchical or multi-level reweighting of the FRS to local population totals. In the /MLV/ simulation, Census tables relating to adults /and/ Census tables relating to households are used, as shown in table above. These are linked respectively to the FRS's =adult= and =household= datasets. This technique is sketched, but not extensively empirically explored, in a conference paper by Müller and Axhausen [[cite:muller_hierarchical_2011][;]]. The procedure adopted here follows that paper, whereby in each IPF iteration, the adult constraint totals are first applied. The arithmetic mean of these weights is then used as the starting weight to fit the household-level constraints. These weights are then in turn applied to all adult household members, and the adult constraints re-applied, and so on, for the desired number of iterations, finally fitting and producing a set of household weights.
** Prior weights from tax income data: /SPI/
An open question in SMS is the specification of the seed or starting weights [[cite:whitworth_evaluations_2013][p30;]]. If each household is given a equal starting weight of, say, 1, as in standard IPF, it implies before constraining the survey data to the local population totals, we have no knowledge of the likely incidence of each household in each area. This may be a reasonable approach, but there may be grounds for using alternative starting weights. For example, when estimating incomes for London boroughs, we assume the starting weight of all London cases from the FRS is 1, but exclude FRS cases from all other regions, effectively assigning them a starting weight of 0.

The second refinement to IPF considered in this paper is additional adjustment to starting weights. A recurring difficulty in the research was in estimating top incomes, particularly in boroughs, such as Kensington and Chelsea and Westminster, where considerable numbers of extremely wealthy households live. This has consequences then for estimates of dispersion and inequality in the local income distributions. There is no apparent way to resolve this with only Census data, since pertitent categorical information, such as being in the highest occupational groups, identifies only a broad sweep of the better-off, rather than the very highest earners. 

Therefore the third variant simulation uses the /Survey of Personal Incomes/ (SPI) to set seed weights and supplement the categorical data used in the other two variants. The SPI data are derived from a large sample of tax return records, and thus provide annual income estimates that are reasonably accurate at borough level, although covering only taxable income of those who make tax returns. SPI data are used in official statistics to improve HBAI estimates estimation of very high incomes [[cite:department_for_work_and_pensions_households_2014][p242;]]. Here the SPI is used to adjust the starting weight of each adult who is believed to have been assessed for income-tax (by having total non-benefits income greater than the personal tax allowance in the relevant year), such that the starting weight reflects the relative probability of an adult with such an income being drawn from the particular distribution of taxable incomes in that local area.

More formally, it assumes that the distributions of adult non-benefit incomes in each borough, and as sampled by the FRS in London, follow a log-normal distribution[[cite:clementi_paretos_2005][;]]. The parameters of this distribution (its mean and standard deviation) in each borough and in London are calculated from the mean and median income figures in the SPI tables published by HMRC. The starting weight of each tax payer in each borough is the probability density of his or her income in the borough distribution, relative to the probability density of the same income in the SPI distribution for London as a whole.

/more formally:/
\[
seed.weight_{ib} = \frac{f(x_{i};\mu_{b},\sigma^{2}_{b})}{f(x_{i};\mu_{L},\sigma^{2}_{L})}
\]

To derive the seed weight of case $i$ in borough $b$: $f(x; \mu, \sigma^2)$ is the probability density of the case's income, $x$, in a lognormal distribution with the parameters \mu and $\sigma^2$, and $b$ and $L$ denote those parameters in a given borough and in London as a whole.  These weights are then scaled so that they sum to $n$, where $n$ is the number of adult cases presumed to be taxpayers. The starting weights of adults who are assumed not to be income-tax payers, having a total non-benefits income of less than the Personal Allowance, is left unchanged at 1.
** Convergence of the three simulations
IPF methods include a set of internal tests which check whether the reweighting procedure has correctly converged, that is, whether population totals using the reweighted dataset are consistent with the known population totals from which the weights are derived. The value of these tests here is primarily to confirm that the variant methods can produce formally correct solutions, and they are presented thus only briefly.

In the tests, the weights derived from the chosen number of IPF iterations (here, 20)  are used to estimate totals of the link variables used in each area. These estimates are compared with the actual local population totals. A summary of this comparison by variable for each variants is given in Table \ref{table:rmse-2001-fit} and Table \ref{table:rmse-2011-fit}. The metric used is the root-mean-squared-error (RMSE) - i.e. the square root of the mean squared differences between each cell in the original constraint table and the corresponding estimate got using the new weights. This measure "can be interpreted as an average difference in the true and estimated frequency count" [[cite:simpson_combining_2005][p225;]]. 

#+NAME: table:rmse-2001-fit-src
#+BEGIN_SRC R :exports results :results output latex
  fit.01 <- cbind(rbind(assess.fit.rmse(ad.cons.01, sim.frsad.01.sl),
                        assess.fit.rmse(hh.cons.01, sim.frshh.01.sl) ),
                  rbind(assess.fit.rmse(ad.cons.01, sim.frsad.01.ml),
                        assess.fit.rmse(hh.cons.01, sim.frshh.01.ml) ),
                  rbind(assess.fit.rmse(ad.cons.01, sim.frsad.01.sp),
                        assess.fit.rmse(hh.cons.01, sim.frshh.01.sp) )
                  )

  fit.01 <- fit.01[,-c(4:6,8:10,12)]

  colnames(fit.01) <- c("Areas", "Classes", rep("RMSE",3))

  latex(fit.01, file="",
        numeric.dollar=FALSE,
        big.mark=",",
        cdec=rep(0,5),
        n.rgroup=c(4,5),
        rgroup=c("Adult", "Household"),
        n.cgroup=c(2,1,1,1),
        cgroup=c("Constraint", "Hhold Only", "Multi-Level", "SPI"),
        caption="Root mean squared error of the constraint variables in the three simulations, 2001",
        label="table:rmse-2001-fit")
#+END_SRC

#+NAME: table:rmse-2011-fit
#+BEGIN_SRC R :exports results :results output latex
  fit.11 <- cbind(rbind(assess.fit.rmse(ad.cons.11, sim.frsad.11.sl),
                        assess.fit.rmse(hh.cons.11, sim.frshh.11.sl) ),
                  rbind(assess.fit.rmse(ad.cons.11, sim.frsad.11.ml),
                        assess.fit.rmse(hh.cons.11, sim.frshh.11.ml) ),
                  rbind(assess.fit.rmse(ad.cons.11, sim.frsad.11.sp),
                        assess.fit.rmse(hh.cons.11, sim.frshh.11.sp) )
                  )

  fit.11 <- fit.11[,-c(4:6,8:10,12)]

  colnames(fit.11) <- c("Areas", "Classes", rep("RMSE",3))

  latex(fit.11, file="",
        numeric.dollar=FALSE,
        big.mark=",",
        cdec=rep(0,5),
        n.rgroup=c(4,5),
        rgroup=c("Adult", "Household"),
        n.cgroup=c(2,1,1,1),
        cgroup=c("Constraint", "Hhold Only", "Multi-Level", "SPI"),
        caption="Root mean squared error of the constraint variables in the three simulations, 2011",
        label="table:rmse-2011-fit")
#+END_SRC

Lower values are "better", and the final constraint applied – here, household type – necessarily has nil error. Beyond this, there are no clear prescriptions as to what values of RMSE and similar measures should be taken as acceptable [[cite:anderson_creating_2007][p14;]]. Here, a sense of the degree of error can be got by considering that London boroughs had in 2011 on average 100,000 households, and that the errors of the multi-level simulation are all less than 1,000 on the household variables.

We can also see that the /HHO/ simulation has substantially greater error in its estimates of adult-level variables, which is as we would expect given that such variables are not controlled for in this variant. The other two simulations, which include adult-level constraints, have much lower absolute RMSE values for the adult variables, whilst increasing the error of the household variables, but by much lower absolute values. This confirms the technical feasibility of multi-level IPF with these data. It may be of interest to note that in the single-level simulation, increasing the number of fitting iterations from 10 to 20 produced virtually no further reductions in error, whereas the error of all variables in the two multi-level simulations was further reduced by doing 20 iterations. Multi-level fitting, understandably, may require more repetitions of the computation steps[fn:1]. The other point of interest is that the use of prior weights in the /SPI/ simulation makes no appreciable difference to the quality of the solution.
* Coherence and Plausibility of the Estimates
These tests of convergence indicate nothing about the value of the income estimates that can be derived from the SMS weights, although such tests are those which most widely appear in the literature. A recent paper goes so far as to argue that "attempts to validate the outcomes of [spatial microsimulation] are relatively weak, and much more strongly focused towards technical checks on the robustness and consistency of procedures than assumptions and outcomes" [[cite:birkin_spatial_2011][p203;]]. A simulation could converge perfectly and still not produce any meaningful estimates of income.

The very endeavour of SMS estimation, however, normally starts from of the absence of direct local observations of the variables of interest, against which the estimates might be tested. An alternative approach is firstly, to test the /coherency/ of the aggregated London results against official published results, and then to check the plausibility of the modelled results using other, related, variables for which small area information is known[[cite:birkin_spatial_2011][p203;]].
** The whole income distribution in London
Although HBAI does not provide borough-level income statistics, it does yield London-wide statistics from its standard weights. In the three simulations, London-wide weights for each case can be got by simply summing its weights in each of the 33 boroughs. With these, we can test the expectation that the London income distributions from the simulations are close to those in the official statistics, and that inconsistencies are explicable.  Figure \ref{fig:orig_v_sim-deciles-2011} presents the decile values of three household income measures: gross income, and income equivalised by the OECD scale before and after housing costs. It compares estimates using HBAI published weights, shown as boxes with confidence intervals, with estimates derived from the three simulations.

#+NAME: fig:orig_v_sim-deciles-2011
#+BEGIN_SRC R :exports results :results output graphics :file fig/orig_v_sim-deciles-2011.pdf :width 4.5 :height 3.5
  deciles <- seq(0.1, 0.9, 0.1)
  inc.vars <- list("EGRINCHH"="Gross income",
                   "S_OE_BHC"="Equivalised income, before housing costs",
                   "S_OE_AHC"="Equivalised income, after housing costs")
  # Return deciles with confidence intervals as a nice dataframe
  deciles.with.cis <- function(dsn, formula) {
      decs <- svyquantile(formula, dsn, seq(0.1, 0.9, 0.1), ci=TRUE, alpha=0.05)
      data.frame(est=decs$quantiles[,], low = decs$CIs[1,,], high = decs$CIs[2,,])
  }

  hbai.11.svy.bu <- svydesign(id=~SERNUM+BENUNIT,
                              weights=~G_NEWBU,
                              data=hbai.11)

  lond.sims.11 <- area.simulations(data.frame(HHO=rowSums(newts.11.sl),
                                              MLV=rowSums(newts.11.ml),
                                              SPI=rowSums(newts.11.sp)),
                                   hbai.11, "SERNUM")

  dec.ests <- lapply(names(inc.vars), function(v) {
      frm <- as.formula(sprintf("~%s", v))
      df <- merge(melt(area.sim.quantiles(lond.sims.11, frm),
                       varnames=c("Simulation", "quantile")),
                  deciles.with.cis(hbai.11.svy.bu, frm),
                  by.x="quantile", by.y=0)
      transform(df, inc.var=inc.vars[[v]])
  })
  to.plot <- do.call(rbind, dec.ests)
  to.plot$decile.g <- as.factor(to.plot$quantile * 100)
  to.plot$sim.dec <- paste(to.plot$Simulation, to.plot$decile.g)

  ggplot(to.plot, aes(x=Simulation)) +
     geom_crossbar(aes(y=est, ymin=low, ymax=high, group=sim.dec), colour=white, fatten=1.5, fill=grey.1) +
     geom_point(aes(y=value, shape=Simulation), size=2, colour=red.2, fill=red.2) +
     scale_x_discrete("", limits=c("HHO", "MLV", "SPI")) +
     scale_y_log10("Weekly income (£, log scale)", breaks=seq(250,1500,250), labels=comma) +
     scale_shape_manual(limits=c("HHO", "MLV", "SPI"),
                        values=c(21:23)) +
     facet_wrap(~inc.var, ncol=1) +
     coord_flip()
    
#+END_SRC

#+LABEL: fig:orig_v_sim-deciles-2011
#+CAPTION[The whole London income distribution, decile estimates from simulations compared to HBAI]: Estimates of decile values of 2011 household income in London (gross, and equivalised, before and after housing costs). Estimates from the published HBAI weights are shown as boxes with the 95% confidence interval. Points show the all-London estimates using the simulation weights. All estimates based on counts of benefit units.
#+RESULTS[ba27ce3d7625857b39b9cd5387349afdf1d64f14]: fig:orig_v_sim-deciles-2011
[[file:fig/orig_v_sim-deciles-2011.pdf]]

For all three simulations, for all three income measures, and at all deciles, the SMS estimates are coherent with the published HBAI estimates, lying within the 95% confidence interval of the HBAI estimates.  The simulations of most interest, /MLV/ and /SPI/ lie especially close to the central official estimate. It is also useful to note that different measures of income (gross and equivalised, before and after housing costs) are coherently estimated from a single simulation. It may thus not be necessary in practice to conduct separate simulations to estimate specific income measures, and rather to "produce transferable models that represent multiple characteristics" [[cite:birkin_spatial_2011][p197;]].
*** Regional accounts measures of household income
The only published UK statistics which offer a measure of household income below regional level are the previously mentioned tables of Gross Disposable Household Income (GDHI). These form part of ONS's /Regional Accounts/, and provide annual figures for regions, NUTS2 and NUTS3 areas, geographic divisions harmonised across Eurostat members. These tables give per-capita figures for "the amount of money that all of the individuals in the household sector have available for spending or saving after income distribution measures (for example, taxes, social contributions and benefits) have taken effect"[fn:9].

Figure \ref{fig:sims-vs-gdhi} presents household income in London's 21 current NUTS3 areas, which each comprise one or more local authorities. The chart compares the GDHI per-capita figures with a per-capita calculation based on the SPI microsimulation results (using the HBAI variable =HNTINCBU=, as the definition of net income closest to that in GDHI). Whilst a broad correlation is apparent, there are very considerable differences in absolute terms and in the relationship between the two measures in each area. This reflects a large gap in both method and definitions. GDHI is based on the downwards apportionment of National Accounts totals; its definition of "households" is correspondingly the "household sector", which includes non-profit institutions like trade unions and universities. The simulation results are bottom-up estimates based on survey microdata. Further reconcilation is not attempted here; it seems more important simply to note that GDHI, though not infrequently used in policy circles, is some considerable distance removed from SMS results based on HBAI, which are more clearly and closely tied to conventional notions of household income and welfare.

#+NAME: fig:sims-vs-gdhi
#+BEGIN_SRC R :exports results :results output graphics :file fig/sims-vs-gdhi.pdf :height 3 :width 4.5
  gdhi <- read_csv("data/gdhin3_tcm77-405127.csv", skip=3,
                   col_types="ccccccccccccccccccccc")
  colnames(gdhi)[1:4] <- c("Area", paste("NUTS", 1:3, sep=""))
  colnames(gdhi)[ncol(gdhi)] <- "2013"
  gdhi <- subset(gdhi, `1997` != "")
  for ( yr in as.character(1997:2013) ) {
      gdhi[,yr] <- as.integer(gsub(",", "", gdhi[,yr]))
  }

  gdhi.ln <- subset(gdhi, Area %in% borough.defs$NUTS315CD)

  ## hbai.01 <- transform(hbai.01, num.ppl = G_NEWPP / G_NEWBU)
  ## sim.hbai.01.sp <- area.simulations(newts.01.sp, hbai.01, "SERNUM")

  ## # HNTINCBU
  ## foo <- area.sim.totals(sim.hbai.01.sp, ~HNTINCBU+num.ppl)
  ## foo <- merge(foo, borough.defs, by.x=0, by.y="LA.NAME")
  ## foo.nuts3 <- aggregate(cbind(HNTINCBU,num.ppl)~NUTS315CD, foo, sum)
  ## foo.nuts3 <- transform(foo.nuts3, inc.per.cap = HNTINCBU / num.ppl * 52)
  ## final <- merge(foo.nuts3, gdhi.ln, by.x="NUTS315CD", by.y="Area")

  ## ggplot(final, aes(x=`2001`, y=inc.per.cap) ) +
  ##     geom_point(aes(label=NUTS3)) + coord_equal()

  hbai.11 <- transform(hbai.11, num.ppl = G_NEWPP / G_NEWBU)
  sim.hbai.11.sp <- area.simulations(newts.11.sp, hbai.11, "SERNUM")
  disp.inc <- area.sim.totals(sim.hbai.11.sp, ~HNTINCBU+num.ppl)
  disp.inc <- merge(disp.inc, borough.defs, by.x=0, by.y="LA.NAME")
  disp.inc.n3 <- aggregate(cbind(HNTINCBU,num.ppl)~NUTS315CD, disp.inc, sum)
  disp.inc.n3 <- transform(disp.inc.n3, inc.per.cap = HNTINCBU / num.ppl * 52)

  final <- merge(disp.inc.n3, gdhi.ln, by.x="NUTS315CD", by.y="Area")

  ggplot(final, aes(y=`2011`, x=inc.per.cap) ) +
      geom_point(aes(label=NUTS3), colour=red.2) +
      labs(x="SPI Simulation net household income per capita, 2011",
           y="Regional Accounts GDHI per capita, 2011")
#+END_SRC

#+LABEL: fig:sims-vs-gdhi
#+CAPTION[Simulation household income per capita against published NUTS3 GDHI, 2011]: Estimates of net household income per capita from the SPI simulation for London's NUTS3 (2015) areas, compared to ONS's published Gross Disposable Household Income per capita figures, from the Regional Accounts.
#+RESULTS[5d4c74d143d51ecf1a2ddbf1f93e43f69eaf1001]: fig:sims-vs-gdhi
[[file:fig/sims-vs-gdhi.pdf]]

** Poverty rates and lower incomes
At the national level, one of the main uses of the HBAI data is the estimation of income poverty rates by reference to the household income distribution, as in the annual DWP publication, /Households Below Average Income/. Comparable poverty measurement at local level is an application of SMS which is of especial policy relevance and interest. Table \ref{table:london_pov_rates-2011} shows poverty rates for London in 2011/12 based on the published HBAI weights and on the simulation output weights. The poverty threshold used is a household equivalised income of less than 60% of the contemporary national median. The table shows that the ratios from the simulations are within ±1% of the HBAI value; this is well within the 95% confidence intervals around the HBAI estimate[[cite:anderson_creating_2007][p14, Table 7;Compare ]]. The SMS results appear then to be coherent estimators of poverty rates. Whilst the Household-Only simulation underestimates poverty compared to HBAI, the two multi-level simulations produce higher estimates.

#+NAME: table:london_pov_rates-2011
#+BEGIN_SRC R :exports results :results output latex
  # Set up a comparison using people weight
  sim.lond.pp.11.cmp <- area.simulations(all.lond.cmp.11, hbai.11, "SERNUM",
                                         with(hbai.11, G_NEWPP / G_NEWBU))
  # Poverty rates for these people
  ln.pov.11  <- t(area.sim.means(sim.lond.pp.11.cmp,
                                 ~LOW60BHC+LOW60AHC)) * 100

  rownames(ln.pov.11) <- c("Before Housing Costs", "After Housing Costs")
  colnames(ln.pov.11) <- gsub("_", " ", colnames(ln.pov.11))
  latex.glove(ln.pov.11,
        title="Poverty rate (people)",
        caption="Poverty rates (percentage of people in relative low income <60\\% of median) 2011, HBAI and simulations",
        cdec=rep(1,4),
        label="table:london_pov_rates-2011")
#+END_SRC

Investigation shows the difference between HBAI and the MLV and SPI simulations to be principally attributable to the differences in weights and implied population totals single people and couples. The Multi-Level and SPI simulations explicitly control for living arrangements (whether an adult is living with a partner) by use of Census data. The grossing control factors used in the HBAI do not control for the marital status or living arrangements of adults, other than the number of lone parent households[[cite:department_for_work_and_pensions_households_2014][p250, Table A.24;]]. HBAI cannot directly use Census data in its grossing scheme, since it must, as an annual survey, produce weights outside of Census years.

#+NAME: table-living-arrangements
#+LABEL: table-living-arrangements
#+BEGIN_SRC R :exports results :results output latex
  fam.units <- area.sim.table(sim.lond.bu.11.cmp, ~NEWFAMBU)

  # People in couple - Census 2011 = 3,111k (DC6401EW)
  # Single people - Census 2011 = 3,339k (DC6401EW)
  fam.tbl <- prop.table(rbind(
      c(3111137, rowSums(fam.units[,c(1,4,6)]) * 2),
      c(3339093, rowSums(fam.units[,c(2,3,5,7,8)])) ),
                        margin=2)
  colnames(fam.tbl)[1] <- "Census 2011"
  colnames(fam.tbl) <- str_replace(colnames(fam.tbl),"_", " ")
  rownames(fam.tbl) <- c("In a Couple", "Not in a Couple")
  latex(fam.tbl, digits=2, file="", title="Data Source",
        n.cgroup=c(2,3),
        cgroup=c("Published Statistics", "Simulations"),
        caption="Proportion of adults aged 16+ living in a couple, 2011",
        numeric.dollar=FALSE,
        label="table-living-arrangements")
#+END_SRC

Single adults, especially those living alone, have higher non-response rates, which are not fully compensated for in HBAI's grossing factors. As table \ref{table-living-arrangements} shows, the published HBAI weights give estimates of the proportion of people living in couples which are much higher than the Census. Since single-adult households (whether pensioners or working age) have lower incomes, especially after housing costs, and, increasingly over the 2000s, higher poverty rates than households with two adults, the official HBAI estimates slightly underestimate the real prevalence of low income and poverty. The slightly higher estimates from the simulation may be regarded as equally or more accurate than the published HBAI results.

Also relevant is the dispersion of poverty rates by borough (analysis and interpretation of these results is taken up in detail in the companion paper). Table \ref{table-districts-pov} shows the highest and lowest poverty rates (after housing costs) for London boroughs. As might be expected, the additional Census information used in the Multi-Level simulation and in the SPI simulation, such as individual ethnicity and living arrangements, substantially increases the estimates of poverty rates for the poorest areas, whilst leaving them little changed in the least-poor boroughs. The addition of tax income data in the /SPI/ simulation changes the estimates of poverty rates hardly at all.

#+NAME: table-districts-pov
#+BEGIN_SRC R :exports results :results output latex
  topbot <- c(1:5,29:33)
  pov.sl <- prop.table(area.sim.table(sim.hbai.11.sl.ppl, ~LOW60AHC),
                       margin=1)
  pov.sl <- pov.sl[order(-pov.sl[,2])[topbot],2]
  pov.ml <- prop.table(area.sim.table(sim.hbai.11.ml.ppl, ~LOW60AHC),
                       margin=1)
  pov.ml <- pov.ml[order(-pov.ml[,2])[topbot],2]
  pov.sp <- prop.table(area.sim.table(sim.hbai.11.sp.ppl, ~LOW60AHC),
                       margin=1)
  pov.sp <- pov.sp[order(-pov.sp[,2])[topbot],2]

  # quick tidy for names
  short.names <- function(foo) {
      gsub("upon Thames", "u.T.", names(foo))
  }

  pov.brg <- data.frame(sl.name=short.names(pov.sl),
                        sl.val=pov.sl,
                        ml.name=short.names(pov.ml),
                        ml.val=pov.ml,
                        sp.name=short.names(pov.sp),
                        sp.val=pov.sp,
                        row.names=c(1:5,29:33))
  pov.brg <- pov.brg[c(1:5, 5, 6:10),]
  pov.brg[6,] <- NA
  row.names(pov.brg)[6] <- " "
  latex(pov.brg, file="", digits=2,
        numeric.dollar=FALSE,
        n.cgroup=c(2,2,2),
        cgroup=c("Hhold Only", "Multi-Level", "SPI"),
        n.rgroup=c(5,1,5),
        rgroup=c("Highest", "", "Lowest"),
        caption="Boroughs with highest and lowest poverty rates (after housing costs) under the three simulations, 2011",
        title="Poverty",
        label="table-districts-pov")
#+END_SRC
*** Deprivation indices and poverty proxies from administrative data
The introduction noted that deprivation indices have wide acceptance and use in policy-oriented analysis of the subregional and small-area distribution of poverty. The best known are the /Indices of Multiple Deprivation/,  a central component of which are estimates of the incidence of income poverty. These are derived fairly directly from administrative records of rates of receipt of means-tested benefits and tax credits.

Since such estimates are necessarily affected by eligibility for and take-up of such benefits, microsimulation estimates have been at various times mooted – and rejected – as a potentially more satisfactory method for estimating local income poverty. A comparison of the simulation results with poverty proxies based on administrative data is thus of interest. Figure \ref{fig:sims-vs-umbr} presents such a comparison. The dataset used is the /Unadjusted Means-Tested Benefits Rate/ (UMBR), a publicly available dataset covering 2001 to 2013. UMBR provides a poverty proxy rate based on the receipt of major means-tested benefits against the mid-year estimated count of households resident in an area [[cite:fenton_unadjusted_2015][;]]. The chart shows this UMBR figure for the 33 boroughs in London in 2001 and 2011, against the poverty rate estimated from the SPI simulations in those years.

In both years, there is the expected positive correlation between the UMBR proxy rate and the simulated poverty rate. It is, however, notable, that this correlation is much stronger and more consistent in 2001 (0.97) than in 2011 (0.84). This is consistent with existing regional analysis, which shows that benefit claim rates became decreasingly well correlated with regional income
poverty rates over the 2000s [[cite:fenton_should_2013][;]]. Reasons for this include the increasing share of in-work poverty; administrative counts of receipt of out-of-work income-replacement benefits are not sensitive to inter-area differences in the extent low pay and high housing costs as a cause of poverty. A detailed discussion of this trend is found in the accompanying paper. Here, the pertinent findings are that the SMS estimates seem highly plausible in the light of administrative poverty proxies, but that the latter have become increasingly weak at identifying inter-area differences in poverty as conventionally conceived.

#+NAME: fig:sims-vs-umbr
#+BEGIN_SRC R :exports results :results output graphics :file fig/sims-vs-umbr.pdf :width 4.5 :height 4.5
  if ( ! exists("umbr.l") ) {
      umbr <- read_csv("~/Documents/DATA/UMBR/umbr14-esw.csv")
      # LSOA to LA, London only
      oa.11.lookup <- read_csv("~/Documents/DATA/BORDERS/lookup/oa_lsoa_msoa_la_lookup.csv")
      lsoa.2.la.ln <- subset(oa.11.lookup,
                             ! duplicated(LSOA11CD) &
                             (LAD11NM %in% borough.defs$LA.NAME))
      umbr.l <- merge(umbr, lsoa.2.la.ln,
                      by.x="Geogcode", by.y="LSOA11CD")
      umbr.l <- merge(umbr.l, borough.defs,
                      by.x="LAD11NM", by.y="LA.NAME")
  }

  la.umbr <- ddply(umbr.l,c("Year", "LAD11NM"), summarise,
                    all.mtb = sum(All.MTB, na.rm=TRUE),
                    hholds  = sum(Hholds, na.rm=TRUE),
                    umbr    = all.mtb/hholds,
                    inout   = InOutLondon[1])

  sims.01.ppl <- area.simulations(newts.01.sp, hbai.01, "SERNUM",
                                  with(hbai.01, G_NEWPP / G_NEWBU) )
  sims.11.ppl <- area.simulations(newts.11.sp, hbai.11, "SERNUM",
                                  with(hbai.11, G_NEWPP / G_NEWBU) )

  la.pov.sims.01 <- area.sim.means(sims.01.ppl, ~LOW60AHC)
  la.pov.sims.11 <- area.sim.means(sims.11.ppl, ~LOW60AHC)

  pl <-rbind(merge(subset(la.umbr, Year==2001), la.pov.sims.01,
                    by.x="LAD11NM", by.y=0),
             merge(subset(la.umbr, Year==2011), la.pov.sims.11,
                   by.x="LAD11NM", by.y=0) )

  # Correlation coefficient
  ## ddply(pl, c("Year"), summarise,
  ##       correl = cor(umbr, LOW60AHC) )

  ggplot(pl, aes(x=umbr, y=LOW60AHC, colour=inout)) +
      geom_point(aes(size=hholds)) +
      # geom_smooth(method="lm", se=FALSE) +
      scale_size_area("Households", labels=comma) +
      scale_colour_manual("", values=colpal.paired) +
      labs(x="UMBR", y="Simulated Poverty Rate (AHC)") +
      facet_wrap(~Year)
#+END_SRC

#+LABEL: fig:sims-vs-umbr
#+CAPTION[Simulated borough poverty rates in 2001 and 2011, compared to the UMBR poverty proxy rate]: Comparison of poverty rates (income less than 60% of national median income, after housing costs) from the SP simulations with the Unadjusted Means-Tested Benefits Rate (UMBR) poverty proxy, by borough, 2001 and 2011.
#+RESULTS[88b2f3fd35ba6d02d6e068a1a71b9f29535a7651]: fig:sims-vs-umbr
[[file:fig/sims-vs-umbr.pdf]]

** Upper incomes and income inequality
As outlined above, a shortcoming of pure-IPF models is that they necessarily use only nominal or ordinal household variables to predict income from local population characteristics. This has particular implications for incomes at the top of the overall distribution. The earned incomes of, say, cleaners, bus drivers or call-centre workers exhibit relatively little variation, and people in such occupations also only rarely have substantial non-earned income from investments. The incomes of higher executives, and of members of some professions, however, vary much more substantially; in London, these categories include people with very high earned and investment incomes. A standard IPF simulation assumes that the whole income range of the managerial-professional occupational group is equally likely to appear in each borough. In fact we know that the "income elite" is disproportionately represented in the central boroughs of Westminster, Kensington and Chelsea and in the City of London, with their more moderately-paid professional peers living in more "average" boroughs. Standard IPF methods simulate only differences at the household level, but not such area effects on incomes.

The /SPI/ simulation adjusted the relative weights given to tax-paying adults with like characteristics but different incomes by reference to income tax data for each borough. The refinement was anticipated to have greatest effect on the upper end of the resulting income distributions. To test this, estimates using the simulated weightings in each borough are compared to the /Annual Survey of Hours and Earnings/ (ASHE), as an independent source with borough-level data. Using FRS and the SMS weights, borough medians of gross weekly earnings (the variable =INEARNS= in the =adults= table) are estimated, considering only full-time employees (=EMPSTATI= == 1). In figure \ref{fig:ashe_earns} these estimates are compared to 2011 ASHE data on gross weekly pay at borough level, showing the range from the 40th to the 60th percentiles.

#+NAME: fig:ashe_earns
#+BEGIN_SRC R :exports results :results output graphics :file fig/earns_v_ashe.pdf :width 4.5 :height 5.5
  ashe <- read.csv("data/ashe-ft_gross_weekly-2011-london.csv",
                   na.string="#")

  ft.emps <- subset(frs.ad.11, EMPSTATI == 1)
  ft.emps.ml <- area.simulations(cbind(newts.11.ml,
                                       "London"=rowSums(newts.11.ml)),
                                 ft.emps, "SERNUM")
  ft.emps.sp <- area.simulations(cbind(newts.11.sp,
                                       "London"=rowSums(newts.11.sp)),
                                 ft.emps, "SERNUM")

  sim.qts.ml <- data.frame(area.sim.quantiles(ft.emps.ml, ~INEARNS,
                                              c(0.25, 0.5, 0.75)))
  sim.qts.ml$Simulation <- "MultiLevel"
  sim.qts.ml$Borough <- row.names(sim.qts.ml)
  sim.qts.sp <- data.frame(area.sim.quantiles(ft.emps.sp, ~INEARNS,
                                              c(0.25, 0.5, 0.75)))
  sim.qts.sp$Simulation <- "SPI"
  sim.qts.sp$Borough <- row.names(sim.qts.sp)

  pay <- merge(ashe, rbind(sim.qts.ml, sim.qts.sp),
               by="Borough",
               all.x=TRUE)
  pay$Borough.Short <- shorten.la.names(pay$Borough)
  # To display in increasing order of pay
  borough.seq <- pay[order(pay$gross.wkly.50,decreasing=TRUE),
                     "Borough.Short"]

  ggplot(pay, aes(x=Borough.Short) ) +
      geom_crossbar(aes(ymin=gross.wkly.40, y=gross.wkly.50, ymax=gross.wkly.60),
                    fill=grey.1, colour=white, fatten=1.5 ) +
      geom_point(aes(y=X0.5, shape=Simulation), colour=red.2, fill=red.2) +
      scale_y_continuous("Full-Time Gross Weekly Pay") +
      scale_x_discrete("", limits=borough.seq) +
      scale_shape_manual(breaks=c("MultiLevel", "SPI"),
                       values=c(22,23)) +
      coord_flip()
#+END_SRC

#+LABEL: fig:ashe_earns
#+CAPTION[Simulation estimates of full-time weekly earnings, compared to ASHE data]: Point estimates of 2011 median gross weekly earnings (full-time employees only) compared to ASHE 40th to 60th percentile range, comparing the MLV (without tax data) and SPI (with tax data) simulations.
#+RESULTS[b8002ec3df718f66c723fdddd75f3594bfc117ad]: fig:ashe_earns
[[file:fig/earns_v_ashe.pdf]]

In the majority of boroughs, the SMS estimates of the median lie just below the 40th percentile in ASHE. This is also true using the standard FRS weightings, reflecting differences in coverage between surveys[fn:6]. However, there are large absolute disparities between the medians derived from the simulations which do not use the SPI data in boroughs with the highest incomes, most markedly in Kensington and Chelsea and the City of London. The additional use of SPI data moves the simulation median of earned income closer to the ASHE median in such boroughs – but at the same time, moves it further away in some boroughs with lower average earnings.

Since the addition of SPI data increases the SMS estimates of upper income, we would expect it also to increase the estimated degree of income inequality in those areas. Table \ref{table-gini-topbot-2011} provides a confirmation of this using the Gini coefficient. The greatest inter-borough income inequality is in the inner London boroughs with the highest top incomes, Kensington and Westminster, and the Gini coefficients increase with the adjustment using SPI data.

#+NAME: Gini
#+LABEL: table-gini-topbot-2011
#+BEGIN_SRC R :exports results :results output latex
  # Comparison between simulations, top and bottom
  gini.11.ml <- apply(newts.11.ml[match(hbai.11$SERNUM,
                                        row.names(newts.11.ml)),],
                      2, gini, x=hbai.11$S_OE_AHC)
  gini.11.sp <- apply(newts.11.sp[match(hbai.11$SERNUM,
                                        row.names(newts.11.sp)),],
                      2, gini, x=hbai.11$S_OE_AHC)

  topbot <- c(1:5,29:33)
  gini.11.sp <- gini.11.sp[order(-gini.11.sp)][topbot]
  gini.11.ml <- gini.11.ml[order(-gini.11.ml)][topbot]


  gini.brg <- data.frame(#sl.name=names(gini.11.sl), sl.val=gini.11.sl,
                         Borough=names(gini.11.ml), Gini=gini.11.ml,
                         Borough=names(gini.11.sp), Gini=gini.11.sp,
                         row.names=topbot)
  colnames(gini.brg) <- gsub("\\..*$","", colnames(gini.brg))
  gini.brg <- gini.brg[c(1:5, 5, 6:10),]
  gini.brg[6,] <- NA
  rownames(gini.brg)[6] <- " "

  latex.glove(gini.brg,
              label="table-gini-topbot-2011",
              title="Gini coefficient",
              caption="Boroughs with highest and lowest Gini coefficients of income inequality (equivalised income after housing costs) under two simulations, 2011",
              digits=2,
              n.cgroup=c(2,2),
              cgroup=c("Multi-Level", "SPI"),
              n.rgroup=c(5,1,5),
              rgroup=c("Highest", "", "Lowest"))
#+END_SRC

The results indicate that the adjusted starting weights produce somewhat more plausible results in a relatively small number of areas with very high incomes. However, aside from the additional data requirements and calculations, the technique has shortcomings, particularly the increased error of estimates in those areas, like Kensington, with a local income distribution that is extreme and distant relative to the all-London distribution sampled by FRS. This is because in the most atypical areas, a small number of FRS/HBAI cases are being used in the SMS to represent a large proportion of the resident households. In Kensington, in the SPI simulation, one single survey case represents over 4% of the resident households (by comparison, a typical household case in HBAI represents 0.05% of London households). It follows from this that estimates of inequality and top income from the SPI SMS are somewhat unreliable and identifying inter-year differences with confidence difficult.

This illustrates how SMS cannot compensate for deficiencies in the coverage of source data. It is only filling in missing data, and where it does this starting from only few observations, as at the top of the income scale, it will perform poorly. Unfortunately, it cannot solve the numerous problems of poor statistical observation of income elites, which affects numerous other official statistics, such as ASHE.
** Income-related household characteristics
So far we have considered the plausibility of income and poverty estimates using the SMS weights. A final test is whether and how well the simulation weights reproduce the distribution of other income-related household characteristics not explicitly controlled for, but for which comparable administrative data exist. This is of relevance also when assessing the potential usefulness of SMS weights for simulating the local effects of policy changes, where reasonably accurate counts of potentially affected populations are important.

The receipt of Housing Benefit (HB) is chosen here as a strongly income-related characteristic of policy interest, as a benefit that is available on a strictly means-tested basis to both private and social tenants in and out of work [[cite:fenton_small-area_2013][;]], and also a policy subject to regular change and, since 2010, large cuts. Figure \ref{fig:hsg-ben} shows the actual and simulated rates of receipt of HB by borough in 2011. The actual counts are DWP administrative data, and the simulated counts are the number of benefit units whose HB receipt is >£0 in HBAI (variable =EHBENBU=). They are expressed as rates per 1,000 benefit units. 

#+NAME: fig:hsg-ben
#+BEGIN_SRC R :exports results :results output graphics :file fig/sim_housing_ben.pdf :height 3.5 :width 4.5
  hb.sim <- area.sim.table(sim.hbai.11.sp, ~(EHBENBU>0))
  colnames(hb.sim) <- c("Not.HB.Sim", "HB.Sim")
  hb.sim <- merge(hb.sim, borough.defs,
                  by.x=0, by.y="LA.SHORTNAME")

  hb.11 <- read.csv("data/london-hb-jun11.csv") # DWP figures
  hb.11$HB.Actual <- as.integer(gsub( "\\,","",hb.11$HB.Jun11))
  hsgben <- merge(hb.11, hb.sim, by.x="Borough",by.y="LA.NAME")

  hsgben$Benefit.Units <- hsgben$Not.HB.Sim + hsgben$HB.Sim

  # The absolute correlation conflates the effect of borough size
  # with(hsgben, cor(HB.Sim, HB.Actual))
  # with(hsgben, cor(HB.Sim/Benefit.Units, HB.Actual/Benefit.Units))
  ## with(hsgben[hsgben$Borough != "City of London",],
  ##      cor(HB.Sim/Benefit.Units, HB.Actual/Benefit.Units))

  ggplot(hsgben, aes(x=HB.Sim/Benefit.Units*1000,
                     y=HB.Actual/Benefit.Units*1000) ) +
    geom_point(aes(size=Benefit.Units, colour=InOutLondon)) +
    ## geom_smooth(method="lm", aes(weight=Benefit.Units), se=FALSE)
    scale_x_continuous("Simulated HB Claims (/1000 Benefit Units)") +
    scale_y_continuous("Actual HB Claims (/1000 Benefit Units)") +
    scale_size_area("Benefit Units", labels=comma) +
    scale_colour_manual("", values=colpal.paired)
#+END_SRC

#+LABEL: fig:hsg-ben
#+CAPTION[Comparison of simulated and actual Housing Benefit claims, 2011]: Simulated against actual housing benefit rates (claims per thousand benefit units), London boroughs, 2011. Simulation SPI against DWP's published figures for June 2011.
#+RESULTS[dd9898f187efb6d5f136106a2c323c765d6ef497]: fig:hsg-ben
[[file:fig/sim_housing_ben.pdf]]

As is normal, counts and rates derived by grossing up from survey-reported benefit receipt are much smaller than the corresponding totals in administrative data. It is the correlation that is of interest, and this (0.87; 0.93 excluding the small and atypical City of London) between the actual and simulated borough rates indicates that the simulation weights effectively, if not fully, estimate inter-area differences in HB receipt. This provides additional confirmation of the usefulness of the simulation in predicting low-income, and, potentially with further adaptation, in the simulation of policy changes.
* Discussion
The paper started with the premise that spatial disparities have been most often discussed either in the form of /differences of aggregates/ – Gross Value Added, employment rates and so forth – which obscure the primary and secondary distribution of income and its relation to income adequacy and well-being, or through the use of deprivation indices, whose methods and sources have tended to detach small-area research on poverty from the methods and terms used in national-level research. This paper extends existing UK work on spatial microsimulation by iterative proportional fitting, as a means for estimating local income distributions that can bridge the gap between these existing approaches. IPF is a fairly straightforward method,  and simulations may be prepared, as in this paper, by use of no more than simple Census population totals and public-use survey datasets.

The analytic part of the paper showed that SMS produced local distributions of income that are coherent with the datasets from which they are derived, and which are plausible when compared to external sources on wages and benefits. One useful finding is that single simulations are capable of producing adequate representations of multiple domains, including different measures of income, its components, and income-related household characteristics like benefit receipt. This lends support to the view that for applied policy analysis, SMS can produce transferrable models that are also suitable for further use in testing policy scenarios.
** The variant techniques
Two modest extensions to existing techniques were examined. The first of these, multi-level IPF, enabled simulation with local area and survey data measured at both the household and adult level, rather than only household data as in standard IPF. In this case, the primary effect of including adult-level data was refined estimation of incomes at the bottom of the end of the distribution. However, the main implications of multi-level IPF are more general. Firstly, it expands the potential range of linking variables which might be used in future simulations - which is more relevant in non-Census years, when a much less rich range of local area totals are available. Secondly, it produces a set of simulation weights that reflect a local population much closer to "reality", thus enhancing the value of the local derived weights for use in policy testing.

The SPI simulation testing altering the starting weights of certain cases by reference to a scalar data source, the Survey of Personal Incomes. The primary effect shown was at the top end of the income distribution, especially in areas which have many highest-income households. That the simulation can be made to converge and produce plausible results when it includes SPI data suggests that these data could be incorporated into non-Census-based simulations. However, the technique means that estimates of top incomes become subject to very considerable uncertainty, which suggests caution about the use of standard inequality measures such as Gini with simulation weights.
** Potential future developments
At the start of the last UK Coalition in 2010, the government returned to a well-established debate in official statistics, that measures of social progress ought to include more than just GDP. So far at least, this is in line with the argument made here that analysis of spatial disparities in economic wellbeing ought to attend, as far as possible, to intra-area distributions as well as inter-area differences. For the purposes of both policy and research, there would be considerable value in having a regularly updated and standard series of sub-regional household-income measures which include distributional information.

Nonetheless, there are obstacles to this. This paper has presented a set of consistent income simulations for two points in time (2001 and 2011), but these time points were dictated by the availability of rich census population data. Inter-censal simulations would need to draw on a wider range of sources, which each bring with them their own difficulties. One route is to make use of regular large-sample surveys, such as the Labour Force Survey, to provide the local population totals to which survey data are fitted. This however means fitting to survey estimates, which have their own (often quite large) uncertainty. Another route is  projection of Census data forwards, as is done for the various official national population projections. Again, this introduces its own uncertainty, and when carried out from scratch is a labour-intensive process [[cite:anderson_creating_2007][;]]. Lastly more use may be made of administrative data, in the way that the Survey of Personal Income and Council Tax records have been used here and in the FRS's grossing controls. This then however adds considerable difficulties of incompatible definitions, under-reporting and differences in populations. Producing compatible survey variables and area counts is likely again to involve estimation and adjustment, even though we know, for example, that there are systematic differences in the survey reporting of benefit take-up between areas [[cite:bramley_benefit_2000][;]].

Whilst this paper has discussed simulated estimates at the level of large local authorities, there is considerable interest in and effort towards simulation and estimation at yet smaller spatial scales in Britain[fn:5].The obstacles described above to the production of local authority simulations outside of census years apply yet more forcefully to neighbourhood-scale geographic units. Supporting survey data from the LFS, ASHE or SPI are of course not usable for such small units. A possible way forward would be to carry out two-stage simulation, first at local authority or county level with the benefit of survey estimates of key household and person characteristics, then at the smaller scale, using the upper-level weights as a starting point, and relying on a mixture of projected Census and administrative data at the smaller level.

This paper has largely left aside the potential (and historically important) use of IPF area weights in policy simulations. These would, for example, bring the kind of modelling of policy changes to taxes and benefits conducted by the Institute of Fiscal Studies at a national level to a local level, to show the spatially differentiated effects of fiscal policy [[cite:ballas_geography_2005,tanton_spatial_2012][;]]. It is probably in this kind of applied research, as much as in the empirical analysis of results as taken up modestly in the accompanying paper, that spatial microsimulation can best make a case for a place in the applied social researcher's statistical toolbox.
* References
\printbibliography[heading=none]

* Footnotes

[fn:10] I am grateful to Ben Anderson for this suggestion.

[fn:4] In 2011, 1.5% of London "usual residents" aged 16 or over lived in communal establishments, with the remainder in private households. Camden, where a large number of student halls of residence are located, has the highest proportion of residents (4%) in communal establishments.

[fn:1] The computational intensity of microsimulation is often remarked on. In a recent paper Tanton et al. report two other simulation techniques taking ½ and 2½ hours for 107 areas [[cite:tanton_comparing_2014][p85;]]. Here, the more complex two-level fitting for 33 areas took about 12 seconds, parallelising the calculation of each area's weights by the =parallel= package included in recent versions of R.

[fn:5] The ONS's small-area income estimates are for MSOAs; Anderson's various simulations, and also the GLA's recent income estimates go down to the smaller, and more widely used LSOA geography.

[fn:6] ASHE is based on a much larger sample from employers' records, but excludes some casual workers and those paid less than the amount at which National Insurance becomes due. In comparison to FRS and other household surveys such as the Labour Force Survey, it covers lowest-paid workers less completely.

[fn:7] The fact that income estimation is being attempted typically implies implies the absence of comprehensive income data against which the precision of any estimate might definitively be assessed

[fn:8] =TODO=

[fn:9] http://www.ons.gov.uk/ons/rel/regional-accounts/regional-household-income/regional-gross-disposable-household-income--gdhi--2013/stb-regional-gdhi-2013.html



